### ISSUE TITLE
Dart VM Appears Broken in 1.26.5 Release

### ISSUE THREAD

**Issue by bdkjones** [sass/dart-sass#1013]
When I download the x64 release of 1.26.5 from this link: https://github.com/sass/dart-sass/releases/tag/1.26.5

And try to run it in Terminal on macOS 10.15.4, I get a `failed to execute binary file` error. If I download the x64 release of 1.26.3 and use the Dart VM bundled in THAT release with the Sass snapshot from 1.26.5, it works fine.

It seems that the Dart VM bundled into 1.26.5 is corrupt? I checked that it was executable on my system (`chmod +x`) and I made no changes to anything after downloading from GitHub—just unzipped the download on my Mac. I have no security software running that might have tampered with the download, etc. I have tried it multiple times, and get the same result each time.

**Comment by jathak** [comment]
Due to an issue with our release process, standalone releases for macOS and Windows didn't get posted for 1.26.5, so you're attempting to run the Linux build on macOS.

Our next release should include macOS builds, but for now, you can download the macOS build for [1.26.3](https://github.com/sass/dart-sass/releases/tag/1.26.3) (there haven't been any behavioral changes between 1.26.3 and 1.26.5.

**Comment by bdkjones** [comment]
Oh, whoops. I didn’t even look that closely—I just saw x64 and grabbed it.
