### ISSUE TITLE
Sass modules @use when files has more than 1 extension or uses dot notation (_settings.config.scss)

### ISSUE THREAD

**Issue by radum** [sass/dart-sass#1065]
Hello,

Thank you for your hard work to everyone involved in this project, I hope everyone is safe and well.

I just started to migrate a large codebase to use the new modules system and I have a question that I couldn't find an answer for in the docs.

Given the following folder structure:

```
├── /styles/
│   ├── /settings/
│   ├── /settings/_settings.global.scss
│   ├── /settings/_settings.grid.scss
│   ├── /main.scss
```

```scss
// main.scss

@use "settings/settings.global";
@use "settings/settings.grid";
```

This returns an error `Error: There's already a module with namespace "settings".\n`

Which means that if I have scss files using the dot (.) notation for separation Sass uses as a namespace value the first word it finds before a dot.

This could be fixed quite simple by using `as` or renaming the files instead of dot to use a hyphen (-). But I was wondering if this has been discussed or if it os a known fact.

One could argue that it is better to use the last one right before .scss is found. Or perhaps the file name should be whatever comes before .scss and the invalid chars could be normalised to - for example.

I was wondering what are your thoughts on this?

Thank you

**Comment by jathak** [comment]
This is intended in the [module system specification](https://github.com/sass/sass/blob/master/accepted/module-system.md#determining-namespaces).

While this does lead to behavior that is perhaps non-ideal in this case, we thought it was simpler to have the default namespace remove all extensions, not just the last one, since they're not usually relevant to the name of the module (except in cases like these where you have two files with the same name and different extensions).

You may find the [module system migrator](https://sass-lang.com/documentation/cli/migrator#module) helpful here, as it will automatically add `as` clauses when two modules' default namespaces conflict.

**Comment by radum** [comment]
Thank you @jathak , that is what I was looking for and it explains the questions I had.
