### ISSUE TITLE
Extending %placeholder with parent reference produce incorrect result

### ISSUE THREAD

**Issue by vkrol** [sass/dart-sass#1066]
Hi. I think I found the bug.
Source:
```
%foo {
    &,
    &.bar {
        color: red;
    }
}

.foo {
    @extend %foo;
}
```
Actual:
```
.foo {
  color: red;
}
```
Expected:
```
.foo, .bar.foo {
  color: red;
}
```
node-sass compiles this as expected.

Minimal reproducible example: https://github.com/vkrol/extend-placeholder-with-parent-reference-sass.

Thanks!

**Comment by jathak** [comment]
Dart Sass's behavior is actually correct here based on the ["laws of extend" in the Sass specification](https://github.com/sass/sass/blob/master/spec/at-rules/extend.md#specificity).

Since `.bar.foo` matches a subset of elements that `.foo` matches, `.bar.foo` can be omitted during the extension. Node Sass's behavior here isn't wrong; Dart Sass's is just more optimized.

**Comment by vkrol** [comment]
Thank you very much, but I still do not understand, the final selector has less specificity, so the laws are violated:
> The second law of extend says that *the specificity* of a new selector to match a given extender *must be greater than or equal* to the specificity of that extender. For example, extend(a, a, a.foo) should produce a, a.foo *even though (again) a.foo matches a subset of elements* matched by a.
