### ISSUE TITLE
Compatibility with node-sass types

### ISSUE THREAD

**Issue by Somnid** [sass/dart-sass#1081]
Hi,

I'm trying to use a custom sass plugin defined for node-sass using the `functions` key passed into the sass render options.  The problem I face is that I get an error because nodeSass.types.Color fails an instance check against dartSass.types.Color when returned.  What are my options here assuming that I don't have access to the plugin?  If I had access to the plugin is there a way to make it universal? 

Do I write some translation layer for the types or is there already a mechanism to do this? (if so, I'm having trouble finding it in the docs)

If there is not already a simple solution for type interop, I'd like to suggest that this be easier.

**Comment by nex3** [comment]
The two JS libraries have the same API surface, but there's no way to make their types mutually compatible. You'd need to pass in the module itself to the plugin, so that the plugin treats `sass` as a variable that could be either `require('node-sass')` or `require('sass')` and calls `sass.types.Color`.

A more reliable and portable way to tell the difference between these types is to call `value.constructor.name`, which will return `"SassColor"` and so on for both implementations.
