### ISSUE TITLE
@use with variables configuration is not applied globally

### ISSUE THREAD

**Issue by monkeythedev** [sass/dart-sass#1084]
I'm using dart-sass through sass-loader.
I found that when importing a module using `@use "module" with {...}`, variables overridden by this configuration are not applied "globally",

I've create a repo to made things clear: https://github.com/monkeythedev/sass-vars-conf-bug

I have an `index.js` file that import 4 scss files.
`test.scss` is the file containing the variable $test.
`test2.scss` override it's value with `@use with`
`test3.scss` uses `test.scss` and output $test value (that results not overriden)
`test4.scss` uses `test2.scss` and output $test value (in this case the value is correct)

![image](https://user-images.githubusercontent.com/53383860/93404302-1e8db480-f88a-11ea-87c6-0fdcca20b0ce.png)

I expect the value to be `right!` event for `test3.scss`.

This is actually a problem while theming a library.
One should be able to theme a library use `@use with`, and all the references to the overridden file inside the library should get the updated values.

**Comment by Awjin** [comment]
This is a great use case for [`@forward ... with`](https://sass-lang.com/documentation/at-rules/forward#configuring-modules). You can configure `test.scss` once, then forward your configuration. This makes it clear which files are depending on the configured `test`, and which ones are using the unconfigured version. For example:

```
<===> test.scss
$test: 'not configured' !default;

<===> configured-test.scss
@forward 'test.scss' with (
  $test: 'configured' !default;
)

<===> test2.scss
@use 'configured-test';
@debug configured-test.$test;  //=> "configured"

<===> test3.scss
@use 'configured-test';
@debug configured-test.$test;  //=> "configured"

<===> test4.scss
@use 'test';
@debug test.$test;  //=> "not configured"
```


More broadly speaking, the removal of global scope was an [intentional design goal](https://github.com/sass/sass/blob/master/accepted/module-system.md#goals) and feature of the module system, put in place to counteract all of the negative effects of global scope.
