### ISSUE TITLE
Can't `@use` a module starting with an underscore then number

### ISSUE THREAD

**Issue by mangelozzi** [sass/dart-sass#1099]
The following would be ideal, but I suspect a module namespace probably can't stop with a number:
```scss
@use "base/1_normalise";
@use "base/2_fonts";
@use "base/3_generic";
etc...
```
So I added a leading underscore to the files:
```scss
@use "base/_1_normalise";
@use "base/_2_fonts";
@use "base/_3_generic";
etc...
```
But this doesnt work either, I think SASS strips the first underscore results in a leading number. Using two leading underscores works (`_1_normalise`). Maybe if the name begins with an underscore then number, it should not strip off the first underscore when creating the namespace, but let it remain in the namespace.

**Comment by jathak** [comment]
`@use "base/1_normalize"` doesn't work because the default namespace would be `1_normalize`, which isn't a valid Sass identifier.

`@use "base/_1_normalize"` also has the same default namespace of `1_normalize`, so it errors for the same reason.

We [remove the leading underscore from default namespaces](https://github.com/sass/sass/blob/master/accepted/partial-namespace.md) because Sass allows partials (files whose names start with underscores and by convention emit no CSS) to be loaded without include the underscore in the URL (e.g. a file named `_partial.scss` can be loaded with `@use "partial"`) and we want the default namespace for a file to be consistent regardless of the URL used to load it.

You can still load a file whose name starts with a number. You just have to give it a different namespace explicitly, e.g.:

```scss
@use "base/1_normalize" as normalize;
```

This explicit namespace can even start with a underscore if you want it to.

**Comment by mangelozzi** [comment]
Thanks for the reply. 

> because Sass allows partials (files whose names start with underscores and by convention emit no CSS)

May I ask where is this documented? I was actually wishing there was such a feature. Reading the [documentation on @use](https://sass-lang.com/documentation/at-rules/use) mentions about private feature of leading _, but I can't deduce the part about emitting no CSS). There seems to be a lot of hidden magic with a leading underscore, which I find hard to understand. Might be worth considering to make the features assoicated with it clealer, and less hidden?

> The @use rule loads mixins, functions, and variables from other Sass stylesheets, and combines CSS from multiple stylesheets together.
