### ISSUE TITLE
Custom importers should allow non-alphabetic characters

### ISSUE THREAD

**Issue by sebakerckhof** [sass/dart-sass#1100]
We're trying to migrate from node-sass to dart-sass.

This allows us to import files from a special package structure like: `@import '{somepackage}/somefile'`
This works fine in node-sass but fails in dart-sass because it checks for a valid url:
`Scss compiler error: Error: Invalid URL: Scheme not starting with alphabetic character`

However, when using a custom importer, dart-sass shouldn't make any assumptions or restrictions on the string we try to import, since it's up to the custom importer function to resolve this.

**Comment by jathak** [comment]
We need to be able to parse all `@import` rules as URLs to be able to distinguish between relative URLs and those that should be passed to custom importers.

LibSass (which node-sass is based on) passes all `@import` URLs to custom importers before checking if they are relative, which allows non-URLs to be used as long as they are captured by a custom importer. However, this behavior is a bug (see sass/libsass#2483), as it means that downstream code could break the relative imports of upstream code by capturing them in a custom importer.

Custom a custom URL scheme instead of `{}` would probably be the most robust option here, as it ensures your imports can be parsed as URLs and avoids conflicts with other potential custom importers, e.g.:
```scss
@import 'meteor:somepackage/somefile'
```

**Comment by sebakerckhof** [comment]
@jathak I read https://github.com/sass/libsass/issues/2483 a bit different, since the author mentions it was meant to work like that. I do understand why you want custom importers to avoid messing with relative imports and the consensus ( https://github.com/sass/libsass/issues/2483#issuecomment-397709510 ) seems to be to indeed explicitly mention when you want to use a custom importer. However our current `{}` is exactly doing that....

So given that, wouldn't the following logic make sense: If the import can not be parsed as a url and there is a custom importer -> pass it down to the custom importer?

It would give more freedom to custom importers, have better compatibility with node-sass/libsass while still allow for dart-sass to handle the relative imports.

**Comment by nex3** [comment]
As Jen mentioned, we need to be able to parse all import strings as URLs because the logic for resolving relative imports is inherently URL-based. For example, `@import 'anotherfile'` needs to be resolved to `meteor:somepackage/anotherfile` if it appears in `meteor:somepackage/somefile` whereas it needs to be resolved to `@import 'file:///path/to/anotherfile` if it appears in `file:///path/to/somefile`. This invariant is crucial for guaranteeing that Sass files can have the same *local* structure regardless of how they're originally located.
