### ISSUE TITLE
Deprecated on NPM, now what?

### ISSUE THREAD

**Issue by Heartnett** [sass/dart-sass#1106]
Now that the project is deprecated on NPM, why not update the README?

Also, what can we now use instead of sass?

![image](https://user-images.githubusercontent.com/11403655/95295044-a7d74c00-0876-11eb-85c3-d8deef96ae27.png)

**Comment by daniluk4000** [comment]
Is it a mistake? I have viewed commit and it's... okay. And it seems like not whole package is deprecated, but only one version, that does not make any sense

**Comment by Heartnett** [comment]
Interestingly, there is a "dart-sass" project on NPM. So going forward do we use this instead?
![image](https://user-images.githubusercontent.com/11403655/95340303-484c6100-08b5-11eb-8e52-0c3bd6887766.png)

**Comment by jathak** [comment]
The intention with that deprecation was to tombstone version 1.26.12 due to a known regression. The package itself is still active and we should have a fixed version up soon.

The `dart-sass` package was identical to the `sass` package, but is no longer up to date.

For the time being, you should use version 1.26.11 of the `sass` package.

**Comment by nex3** [comment]
Yeah, we *specifically* marked version 1.26.12 as deprecated so that npm wouldn't install it by default because of the JS API regression. I didn't realize that npm would display that banner for the entire package.

A new release is coming this afternoon that will clear out the banner.
