### ISSUE TITLE
Cannot symlink sass on Linux

### ISSUE THREAD

**Issue by BenMorel** [sass/dart-sass#1117]
I've extracted the dart-sass dir to `~/bin/dart-sass`, and symlinked `sass`:

```bash
cd ~/bin
ln -s dart-sass/sass sass
```

But running `sass` from any directory gives an error:

```
$ sass
/home/benjamin/bin/sass: 17: exec: dart-sass/src/dart: not found
```

Changing the `sass` script this way works for me:

```diff
16c16
< path=`dirname "$(follow_links "$0")"`
---
> path=`dirname "$(follow_links $(realpath "$0"))"`
```

I didn't find where this script is hosted to open a PR.

**Comment by jathak** [comment]
Our releases are built with [dart_cli_pkg](https://github.com/google/dart_cli_pkg). This bug is tracked there in google/dart_cli_pkg#43.

We'd welcome a PR there to fix this (the scripts are [here](https://github.com/google/dart_cli_pkg/tree/master/lib/src/templates/standalone)), but we need to make sure the solution used works on both Linux and macOS (`realpath` does not, unfortunately).

**Comment by BenMorel** [comment]
Thanks for the pointer (and sorry for the dup). I'm not familiar enough with macOS, and from a quick search, a lot of shell scripts attempt to replicate the `realpath` behaviour but always end up having some edge cases.

How feasible is it to ship a `realpath` binary with dart-sass, together with the Dart VM? A simple [wrapper around C's `realpath()`](https://stackoverflow.com/a/46772980/759866) would be enough.

**Comment by jathak** [comment]
I think the barrier to shipping any binary is code signing (especially on macOS), which is the reason we're shipping an AOT snapshot + the Dart VM at all (if we didn't have to worry about code signing, we could just ship a single Sass executable and not have to deal with a wrapper script at all).
