### ISSUE TITLE
Importer incorrectly excludes files by filename, instead of absolute path, when using contents option 

### ISSUE THREAD

**Issue by clshortfuse** [sass/dart-sass#1121]
Simply put, when using `contents` instead of `file`, `Importer` will not consider the full path of the file, but only look at the filename itself. If the same filename appears in two subfolders, `Importer` will not process (perhaps because of cache) any files name that match.

Example Tree:

- /index.scss
- /folder1/
  - useAandB.scss
  - a.scss
  - b.scss
- /folder2/
  - useAandB.scss
  - a.scss
  - b.scss

Sample code:

````js
const sass = require('sass');
const path = require('path');

const rootIndex = `
@use './folder1/useAandB.scss' as folder1;
@use './folder2/useAandB.scss' as folder2;
`
const useAandB = `
@use './a.scss';
@use './b.scss';
`;

const folder1a = '.folder1a{content:"folder1a"}'
const folder1b = '.folder1b{content:"folder1b"}'
const folder2a = '.folder2a{content:"folder2a"}'
const folder2b = '.folder2b{content:"folder2b"}'

function getContents(path) {
  switch (path) {
    case '/index.scss':
      return rootIndex;
    case '/folder1/useAandB.scss':
      return useAandB;
    case '/folder2/useAandB.scss':
      return useAandB;
    case '/folder1/a.scss':
      return folder1a;
    case '/folder1/b.scss':
      return folder1b;
    case '/folder2/a.scss':
      return folder2a;
    case '/folder2/b.scss':
      return folder2b;
    default:
      throw new Error("NOT_FOUND");
  }
}

const rootPath = '/index.scss';
const locationMap = new Map();
const result = sass.renderSync({
  data: getContents(rootPath),
  outputStyle: "compressed",
  importer(url, prev) {
    let requester = locationMap.get(prev);
    if (!requester) {
      console.assert(prev === 'stdin', 'stdin');
      requester = rootPath;
    }
    const dirname = path.dirname(requester);
    const request = path.join(dirname, url);
    locationMap.set(url, request)
    console.log(requester, '=>', request);
    const contents = getContents(request);
    return {
      contents,
    };
  }
})
const actual = result.css.toString();
const expected = [
  folder1a, folder1b, folder2a, folder2b
].join('');

console.assert(actual === expected , 'CSS Match', {actual, expected}, result.stats.includedFiles);
````

Output:
````
/index.scss => /folder1/useAandB.scss
/folder1/useAandB.scss => /folder1/a.scss
/folder1/useAandB.scss => /folder1/b.scss
/index.scss => /folder2/useAandB.scss
/folder2/useAandB.scss => /folder2/a.scss
/folder2/useAandB.scss => /folder2/b.scss
Assertion failed: CSS Match {
  actual: '.folder1a{content:"folder1a"}.folder1b{content:"folder1b"}',
  expected: '.folder1a{content:"folder1a"}.folder1b{content:"folder1b"}.folder2a{content:"folder2a"}.folder2b{content:"folder2b"}'
} [
  'folder1/useAandB.scss',
  'a.scss',
  'b.scss',
  'folder2/useAandB.scss',
  // Removed Symbol
]
````

Changing `folder2` to contain `c.scss` and `d.scss`, instead, produces the correct result (4 rules instead of 2). `includedFiles` shows that the full path isn't being used.

**Comment by clshortfuse** [comment]
I believe the bug can possibly be here: https://github.com/sass/dart-sass/blob/39358fbb7b0c54c265305a319d93287b02f18d7e/lib/src/importer/node/implementation.dart#L186

Specifically, `previous` is not used to rebuild the real path and just the `url` is used instead.

**Comment by clshortfuse** [comment]
Returning `p.join(p.dirname(p.fromUri(previous)), url)` indeed solves the problem. Now to test and spin up a PR.

**Comment by clshortfuse** [comment]
Well, it seems there's a real fundamental issue with how `@use` loads modules. Because it must use a `Uri` object, it's completely ambiguous whether a the `url` references a file that exists on a path system or the name of a package. In other words, it's ambiguous if `foo` exists as a file in the folder it's being loaded from, or if `foo` is a package that need an importer to point to.

I thought that maybe we can differentiate `foo` the package, with `./foo` the file, but because calls `Uri.parse(url)`: 
https://github.com/sass/dart-sass/blob/8e35a4473d84870e9c7fa3772a2d886fe18d02b9/lib/src/parse/stylesheet.dart#L3476 that means even writing `./foo` will normalize it down to just `foo` making it's ambiguous again. It seem `dart-sass` is extremely dependent on raw access to the system's filesystem to work around this, but this doesn't help when it's using virtual files (eg: loading from S3, database, or memory store).

I see a couple possible solutions:

1. Strip the Uri and instead use a `string`, much like was done for `@import` when closing https://github.com/sass/dart-sass/issues/246
2. Detect if the url is a relative path instead of an absolute one. For example, if `./*` is used, then the `Uri` should be constructed relative to the current stylesheet's url.
3. If a file imported with both `file` and `contents`, `dart-sass` should not abort when a file is not found. Instead, it should ask the importer to provide the content. This allows support for custom scheme, (eg: `https://`, `s3://`, `virtual://`, etc).
4. Allow the importer to dictate the absolute (full) url. This prevents `dart-sass` from caching against the wrong URL.
5. Allow the filesystem resolution to be disabled. `dart-sass` will never attempt to read a file on its own, and instead always ask the importer to provide the contents.

I'm leaning to option 3, specifically because, I don't think `dart-sass` should downright fail if the `Importer` can provide the `contents`. In the event the `Importer` cannot provide data for the url that has been request, *then* it should fail.

**Comment by clshortfuse** [comment]
Well, it looks like option 3 is actually the intended implementation, (albeit limited to scheme of `''` or `file://`). 

https://github.com/sass/dart-sass/blob/39358fbb7b0c54c265305a319d93287b02f18d7e/lib/src/importer/node/implementation.dart#L164-L175

`_tryPath` is missing a `try`/`catch`. Once that's added, when a file can't be found it'll defer to the Importer.

**Comment by nex3** [comment]
What you're seeing is an unfortunate side effect of the Node.js importer API that we inherited from Node Sass. This API is kind of messy, without a clear distinction between URLs that are handled natively by the Sass implementation and URLs that are handled by importers. Unfortunately, for compatibility reasons we aren't able to modify it very deeply; instead, we're planning on replacing it with a new and improved API that handles these behaviors in a much more principled way (https://github.com/sass/sass/issues/2509).

Let me try to clearly explain the behavior you're seeing. Keep in mind the [Node API import order](https://sass-lang.com/documentation/js-api#importer) while reading this.

* First, you tell Sass to render

   ```scss
   @use './folder1/useAandB.scss' as folder1;
   @use './folder2/useAandB.scss' as folder2;
   ```

   Because you don't supply a `file` parameter, as far as Sass is aware this module has no canonical URL and cannot be referenced by other files.

* Sass loads the (relative) URL `folder1/useAandB.scss`. Since it can't resolve this relative to the containing file's canonical URL, it passes it straight to an importer. The importer returns the contents 

   ```scss
   @use './a.scss';
   @use './b.scss';
   ```

   Because the importer doesn't return an associated `file` field, Sass uses the relative URL `folder1/useAandB.scss` as this module's canonical URL.

* Sass loads the (relative) URL `a.scss`. Because the previous canonical URL is not a `file:` URL (it's relative, which is effectively considered to be a unique scheme in and of itself), Sass can't automatically resolve this to a file on disk, so instead it passes it directly to the importer.

   In an ideal world, Sass would recognize that `a.scss` is relative to `folder1/useAandB.scss` and pass the importer `folder1/a.scss` before passing it `a.scss` as a separate string. However, as I mentioned before, this would break compatibility with the Node Sass importer API, which does no pre-processing of URLs before passing them to importers.

   So the importer is passed `a.scss` as `url` and `folder1/useAandB.scss` as `prev` and returns `.folder1a{content:"folder1a"}`. Again, because it doesn't return a `file` field, the canonical URL of this module is `a.scss`.

* The `b.scss` load and the `folder2/useAandB.scss` load happen in a similar way to the above.

* Now Sass goes to load the (relative) URL `a.scss` from `folder2/useAandB.scss`, which initially works the same as it did in `folder1`. This means that the canonical URL is still just `a.scss`, though, and two `@use` rules that resolve to the same canonical URL must load the same module. So rather than processing the stylesheet your importer returned, Sass just loads the same `a.scss` module it loaded the first time.

If you were using the Dart importer API (which we plan to use as the basis for the new Node importer API), this would work differently. In that system, all stylesheets are required to have *absolute* canonical URLs, which disambiguates stylesheets that exist on the actual filesystem and those that are loaded from virtual sources. And relative URLs are first resolved relative to the parent stylesheet's (again, absolute) canonical URL and passed to the same importer to determine if it can be loaded relative to the stylesheet, and then passed to other importers to determine if it can be loaded as a global name.

**Comment by clshortfuse** [comment]
@nex3 Thanks for taking a look. I appreciate the long response and the time you took to write it. I had already figured out the way it works, understanding the compatibility issues and why there is no straight, easy fix. Most changes would be too invasive.

Still, I was trying to figure out a way to workaround without breaking anything. I can handle figuring out what's relative and on my (the developer side). Still, I suggest you take another look at the PR.

> Returns the stylesheet at that path and the URL used to load it, or `null` if loading failed. 

And it doesn't. It fails and throws an error, terminating the process. I don't think that's working as intended. Either the code should be fixed to return what it should (`null`) or the documentation should be fixed to reflect that `tryPath` doesn't actually perform a `try` (instead it's more getPath). It honestly seems like an oversight. That then gives more preference to the Importer which seems the actually intended effect.

**Comment by clshortfuse** [comment]
To expand:

>Imports are resolved by trying, in order:

> * Loading a file relative to the file in which the @use or @import appeared.

> * Each custom importer. 

> * Loading a file relative to the current working directory.

> * Each load path in includePaths

> * Each load path specified in the SASS_PATH environment variable, which should be semicolon-separated on Windows and colon-separated elsewhere.

https://sass-lang.com/documentation/js-api#importer

Again, sounds like the the intended behavior is to let the importer handle it when it doesn't find it. The first time it goes through the loop, the custom importer returns the file it needs as well as a file location (even if virtual). On subsequent request, it fails at the first step and aborts before asking the importer (which can indeed supply the contents).

More precisely, the custom importer takes `stdin` and responds with a `contents` and `file`. `dart-sass` is trying to figure out the next import on it's own. It can't, it fails, and it closes down, instead of continuing the try sequence.
