### ISSUE TITLE
at-rule values do not support `!` character

### ISSUE THREAD

**Issue by thelornenelson** [sass/dart-sass#1158]
Dart-sass can't successfully handle at-rules where the value contains the `!` character - this may be intentional but unsure why that would be the case.

## For example this code compiles fine

Input
```scss
@custom-at-rule boom {
}
```

Output
```css
@custom-at-rule boom {}
```

## This code doesn't compile:

Input
```scss
@custom-at-rule boom! {
}
```

Result:
```
Error: expected ";".
  ╷
1 │ @custom-at-rule boom! {
  │                     ^
  ╵
  test.scss 1:21  root stylesheet
```

Node-sass by contrast handles this fine. Maybe related to dart-sass allowing interpolation in at-rule names?

**Comment by Awjin** [comment]
Dart Sass's behavior is correct here—the name of an at-rule needs to be a valid identifier. If you want to use `!` in the name, it must be escaped.

```
@custom-at-rule boom\! {}
```

**Comment by thelornenelson** [comment]
@Awjin You are correct about the at-rule *name*, but this concerns the at-rule *value*, which does not have to be a valid identifier. 

```
@[at-rule-name] [at-rule-value which can be basically anything] {
optional at-rule block
}
```

**Comment by nex3** [comment]
Currently we parse at-rule values as [`<declaration-value>`](https://www.w3.org/TR/css-syntax-3/#typedef-declaration-value) productions (with the addition of support for interpolation). Since `<declaration-value>` stops at `!`, at-rules do as well. But there's no inherent reason for this; feel free to file an issue on https://github.com/sass/sass to change it.
