### ISSUE TITLE
About node_preamble.dart...

### ISSUE THREAD

**Issue by Mstrodl** [sass/dart-sass#1166]
Hi there, I've been trying to get [my pull request to node_preamble.dart](https://github.com/mbullington/node_preamble.dart/pull/21) merged for the past 3 months or so to no avail. I've been bumping the issue every two weeks or so and eventually tried emailing him about 2 weeks ago, but he hasn't responded to either. His account isn't dormant; there's still activity on GitHub, but I don't think there's any way to get in touch with him. [This is not the first time this has happened](https://github.com/mbullington/node_preamble.dart/pull/20).

Therefore, I'm proposing a fork of node_preamble.dart that will be better maintained and I wanted to get some opinions as dart-sass is the project I'm trying to use that requires it.

CC @jathak, as she has [an open PR on the repo](https://github.com/mbullington/node_preamble.dart/pull/22) as well

**Comment by nex3** [comment]
Let's wait until the new year to figure this out. We can adopt ownership if we need to, but these are strange times and I understand if @mbullington is just busy right now.

**Comment by Mstrodl** [comment]
@nex3 Sure. I just wanted to make sure this was something we talked about, because my project has been broken for the past few months.

**Comment by mbullington** [comment]
Hey all.

@Mstrodl thanks for reaching out to me a bunch, I understand your frustration and have been meaning to respond. I've been just busy and juggling lots of responsibilities, but `node_preamble` has been on my TODO list since your first message.

Truth is—I agree with @Mstrodl. I haven't directly used `node_preamble` for years, most of my work now is merging others PRs and doing manual QA since `node_preamble` has so many different environments to work on.

Having more maintainers sounds fine to me, as long as we're checking each others work via Code Reviews first. Thinking about the stakeholders here: @nex3 @Mstrodl @jathak @pulyaevskiy @lexaknyazev (let me know if I forgot anyone!)

Would we want to move `node_preamble` to a more neutral location as well? Don't want to impose here but an existing org may be better suited than just my personal GitHub.

**Comment by jathak** [comment]
Adding more maintainers makes sense to us. There isn't really an existing org that would work to move it to, but you could perhaps make a new `node_preamble` org for it if you don't want it in your personal GitHub.

**Comment by Mstrodl** [comment]
@mbullington That sounds reasonable to me, personally I don't see any real value in moving it to its own org, but I do agree adding more maintainers is a good idea (with code reviews, obviously). Sorry if I've been a bother the past few months.

**Comment by mbullington** [comment]
Following up on this, I'm adding @jathak @Mstrodl @nex3 as maintainers and the code review checks we discussed. If anyone else mentioned above would like maintainer access, please let me know and I'll be happy to.

**Comment by nex3** [comment]
Thanks Michael! Can you add @Awjin as well? He's also a member of the Google Sass team.

**Comment by mbullington** [comment]
Done!
