### ISSUE TITLE
10 digits of precision aren't always guaranteed

### ISSUE THREAD

**Issue by oscarmarcelo** [sass/dart-sass#1167]
I've been making some tests with big decimals and I found out that numbers bigger than 1048576 doesn't output with the precision of 10 digits:
```scss
// ✅
@debug 1048575.9999999999; // DEBUG: 1048575.9999999999

// ❌
@debug 1048576.0000000001; // DEBUG: 1048576
@debug 1048576.123123123123123; // DEBUG: 1048576.123123123
@debug 123456789.123123123123123; // DEBUG: 123456789.12312312
```

Additionally, some other tests also revealed that some numbers smaller than 1048576 with exactly 10 digits after the decimal point are rounded to 9 digits:
```scss
// ❌
@debug 1048575.0000000011; // DEBUG: 1048575.000000001
@debug 1048575.4111111111; // DEBUG: 1048575.411111111
@debug 1048575.9111111111; // DEBUG: 1048575.911111111
```

**Comment by nex3** [comment]
This is because Sass stores numbers as [floating points](https://en.wikipedia.org/wiki/Floating-point_arithmetic), which inherently loses accuracy when a number is both very large *and* contains a fractional component. You can see the same effect if you write these numbers in your browser console:

![image](https://user-images.githubusercontent.com/188/102940047-49c50880-4464-11eb-8af9-b0ea04a06fe0.png)
