### ISSUE TITLE
Offer pre-built *BSD binary?

### ISSUE THREAD

**Issue by o-alquimista** [sass/dart-sass#1173]
I would like to suggest adding BSD binaries at least for FreeBSD (which seems to be the most popular among BSD systems). I'm currently experimenting with FreeBSD at home for the first time and this is one of the tools that lack support for it.

Eventually I want to migrate my personal server to a BSD system, so it would be great to be able to compile assets with it every time there's an update to the web apps I'm running.

I understand that supporting another platform is not a simple task and that there are many ways to work around this limitation; for example, building assets on a supported system and transferring the built files, or using the node `sass` package (right?). So this is just a "good to have" thing, I believe.

**Comment by jathak** [comment]
Unfortunately, there's no way for us to provide a native BSD binary without the Dart SDK adding support for it. You could try [filing an issue there](https://github.com/dart-lang/sdk/issues) to add support. While this would allow you to build a native BSD binary yourself, actually including BSD binaries in our releases on GitHub would also require our CI to support building on BSD, which it currently does not.

The `sass` package on NPM is compiled to JS from Dart, so it has the same behavior as native Dart Sass (unlike the `node-sass` package, which is based on the deprecated libsass), just with a performance penalty due to running in JS (which shouldn't be a practical issue except for very large projects). If you install it with `npm install -g sass`, you should get a `sass` executable with the same behavior as a native binary.

**Comment by nanaya** [comment]
A over year late response but if this is any indication, there's little chance of freebsd port happening:

https://github.com/dart-lang/sdk/issues/10260

I'd suggest either hope the js compiled sass is good enough or use something else. The former may be a bit more difficult when using additional wrappers like dartsass-rails though...
