### ISSUE TITLE
Deprecation Warning: $saturation: Passing a number without unit % (0) is deprecated.

### ISSUE THREAD

**Issue by jsg2021** [sass/dart-sass#1203]
Can `0` have a special case? I've had to pin to 1.30.0 because a library I do not maintain uses a value `hsla(0,0,0,.025);` and this blows up my build.  Stylelint often encourages dropping units on 0.

https://github.com/sass/dart-sass/blob/01231e2f4cf2910d0ac3a2057670829fd5b24bbd/lib/src/functions/color.dart#L670-L675

**Comment by nex3** [comment]
We want to match CSS's behavior here and `hsla(0, 0, 0)` is [not valid CSS](https://codepen.io/nex3/pen/poExaNd). I believe stylelint will only suggest dropping units for 0 when it's used as a [`<length>`](https://codepen.io/nex3/pen/poExaNd), but if that's not the case that's a stylelint bug.

Note that this will remain a deprecation warning until Dart Sass 2.0.0—the only behavior that will change before then is passing non-`deg` angle units like `rad` or `turn`. You don't need to pin your Sass version, since nothing's going to break in the short term.

**Comment by jsg2021** [comment]
good to know, but the warning itself breaks sass-loader (makes webpack crash hard)

**Comment by nex3** [comment]
I recommend filing an issue against sass-loader for that. Sass strongly assumes that it's able to produce deprecation warnings without them being breaking.

**Comment by jsg2021** [comment]
Oh, I'm sorry! I was in the middle of preparing dinner for the fam. I wasn't trying to say sass was at fault or wrong. I have opened a bug there. :)

**Comment by jsg2021** [comment]
I've worked around all this, so there is no rush or pressure to act. I'm just adding documentation :)
https://github.com/webpack-contrib/sass-loader/issues/914

I believe there is an error in dart-sass when raising the deprecation warning in a Fiber ...or there is an error with toString implementation of the warning...
```
ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: NoSuchMethodError: method not found: 'get$span' on null
   ╷
25 │ $side-nav-link-bg-hover: hsla(0, 0, 0%, 0.025) !default;
   │                          ^^^^^^^^^^^^^^^^^^^^^
   ╵
``` 

Specifically the `NoSuchMethodError: method not found: 'get$span' on null`
