### ISSUE TITLE
Function call inside color.scale() not working

### ISSUE THREAD

**Issue by miraidesigns** [sass/dart-sass#1213]
Hey there,

I just recently made the switch to sass-dart trying to master the new modular approach with @use and @forward. I started a completely new project, based on a framework I am writing, and I am trying to convert my old files to new ones.

I have a map consisting of colors that I use for theming purposes, like so:

```
$colors: (
    'grey': #9E9E9E,
    'red': #F44336,
    'pink': #E91E63,
    'purple': #9C27B0,
    'blue': #2196F3,
    'cyan': #00BCD4,
    'teal': #26A69A,
    'green': #4CAF50,
    'yellow': #FFEB3B,
    'orange': #FFA726,
    'deep-orange': #FF5722,
) !default;
```

I have then written a simple function to get a given value from that map:
```
@use "sass:map";

@function getColor($key) {
    @return map.get($colors, $key);
}
```

But trying to manipulate that color through the color module, leads me to this error:
```
@use "sass:color";

color.scale(getColor('red'), $lightness: 7%);
```
```
$color: getColor('red') is not a color.
```

I don't know if I am doing it wrong or if this is the intended behavior or if I can correct it in some way to make this approach work.

Thank you for your time.

**Comment by Awjin** [comment]
All the code you've posted here is good, and it compiles correctly for me. We'd need more context to figure out how exactly it's breaking. Some possibilities: Are you calling a different function `getColor()` that has the same name, but doesn't actually return a color? Did you override the `'red'` value in `$colors` with a different non-color value, so that `getColor()` no longer returns a color?

**Comment by miraidesigns** [comment]
That was absolutely my mistake, yeah. Reading your response made me take a good look at my code again and there was some cross-referencing that made the variable lose the correct value. Thanks again for the help.
