### ISSUE TITLE
Alias "-t" flag from Ruby Sass?

### ISSUE THREAD

**Issue by haengle** [sass/dart-sass#1218]
Hello,
I am trying to migrate my team from Ruby Sass to Dart Sass. We have 200+ projects using Composer/Apache Ant where the CSS build arg uses the "-t compressed" flag from Ruby Sass that is not available in Dart. 

Will "-t" be added as an alias or is there another workaround? I will not get approval to migrate if we have to manually touch each project to update this alias.

Thanks y'all!

**Comment by jathak** [comment]
`-t` isn't an abbreviation that makes sense, so the decision to omit it from Dart Sass's CLI was intentional. `--style` or `-s` for short are the accepted flags for this option in Dart Sass.

If updating your command line is truly infeasible, you could try writing a wrapper script around Dart Sass that converts your legacy CLI to the form accepted by Dart Sass.
