### ISSUE TITLE
Check for Deep Call Stack

### ISSUE THREAD

**Issue by procd92** [sass/dart-sass#1243]
Hey everyone,
I hope you have a beautiful day.

I really don't know how to write a good title, but I hope this explanation will demonstrate the issue.

I have been writing a lot of Sass for a project and after some changes noticed that Node process will just run out of memory, even if I have inceased it to 8096 MB, no luck.

I have made a mistake in writing my Sass code, but couldn't get any hint about the mistake other that `out of heap memory`.

Here is the problem:

```sass
@mixin some-mixin {
    @include some-mixin;

    // Code...
}
```

Now this caused an infinite recursion that went unnoticed by `dart-sass`. Is it possible that some detection for this case can be implemented for the library?

Here is how `node-sass` handles the problem:

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: SystemStackError: stack level too deep
        on line 4 of src/style/mixins.scss, in mixin `some-mixin`
        from line 4 of src/style/mixins.scss, in mixin `some-mixin`
        from line 4 of src/style/mixins.scss, in mixin `some-mixin`
        from line 4 of src/style/mixins.scss, in mixin `some-mixin`
        # .......
```

Thank you for your amazing work ❤️

**Comment by Awjin** [comment]
Compiling synchronously instead of asynchronously might provide a better stack.

We *might* be able to update the Sass evaluator so that when it detects a recursion, it also tracks the stack level, then throws an error if it exceeds a certain threshold. However, this wouldn't account for the underlying OS and how deep of a stack level the OS tolerates, which is usually how the threshold is determined. It's also a leaky abstraction to have Sass handle memory issues.

Since this is really a Dart2Js issue and would be best handled there, I'll close this issue.
