### ISSUE TITLE
CI is broken since the Dart 2.12 stable release

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1254]
There are 2 things breaking:

- the node.js tests are apparently trying to spawn an isolate with sound null safety turned on, which fails as null safety is not yet ready (#1253 is working on implementing null safety)
- the analyzer jobs fails because the new version has some new checks

**Comment by jathak** [comment]
The Node tests issue is due to a bug in the Dart SDK itself. I believe they're working on a fix, but we'll likely complete the null safety migration before that's done.

If there's an urgent need to cut a release before we finish the null safety migration, we can pin the CI to Dart 2.11, but otherwise, we can just wait to merge other PRs until #1253 is done.

**Comment by stof** [comment]
@jathak I see that #1253 has been closed without merging it. So what is the state of this work ?

**Comment by Awjin** [comment]
@stof We're still working on the nnbd migration, but in a different branch.
