### ISSUE TITLE
Color name warning should not apply to selectors

### ISSUE THREAD

**Issue by robmadole** [sass/dart-sass#1255]
Font Awesome is working on version 6 and we had a customer report the following error using dart-sass. (I'm editing the original issue as it's from a private repo.)

When compiling (using dart-sass 1.32.5) i get this warning:

```WARNING: You probably don't mean to use the color value wheat in interpolation here.
It may end up represented as wheat, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "wheat").
If you really want to use the color value here, use '"" + $name'.

  ╷
8 │   .#{$fa-css-prefix}-#{$name}::before { content: fa-content($icon); }
  │                        ^^^^^
  ╵
    node_modules/@fortawesome/fontawesome-pro/scss/_icons.scss 8:24       @import
    node_modules/@fortawesome/fontawesome-pro/scss/fontawesome.scss 18:9  @import
```

This usage of the "wheat" name does not present any danger of getting misinterpreted in the context of a selector. Can this warning be improved so that it doesn't present these in these types of cases?

**Comment by stof** [comment]
The issue is not about being misinterpreted as a selector, but about being misinterpreted in the context of the place where you defined your name used in the interpolation.

Here, `$name` is a SassColor, not a SassString. The interpolation serializes the value to its string representation.
The only reason why the output works as `wheat` is because the serializer prefers reusing the original representation of a color in expanded mode if it has one (and the interpolation always serializes the value using the expanded styles): https://github.com/sass/dart-sass/blob/3d39f22cbff8097c212dd90a507c22dd808c3f19/lib/src/visitor/serialize.dart#L478-L522

But if the implementation changes, this could start producing `.fa-#f5deb3::before` instead.

**Comment by robmadole** [comment]
Here is the context then:

```
@each $name, $icon in $fa-icons {
  .#{$fa-css-prefix}-#{$name}::before { content: fa-content($icon); }
}
```

And the `$fa-icons` is defined like this (abbreviated for brevity):

```
$fa-icons: (
  wheat: $fa-var-wheat,
)
```

Why would that, by default, produce a `SassColor`?

**Comment by stof** [comment]
because `wheat` is a SassColor when parsing scss, not an unquoted string (because that's a valid CSS named color).

Keys in Sass maps can be any kind of values, not only strings. So there is no reason to change the parsing of `wheat` inside a map key compared to elsewhere in Sass (which would also create issues as `map.get($fa-icons, wheat)` would still have to parse `wheat` as a SassColor and would then not find the key). So there is no way to change that without removing support for named colors in Sass AFAICT.

the fact that some other type of Sass values *look like* unquoted strings is precisely the reason why the documentation about maps recommends using quoted strings rather than unquoted string to avoid such issues: https://sass-lang.com/documentation/values/maps

**Comment by robmadole** [comment]
Ok great, thanks @stof.

So would this cleanly fix the issue?

```
$fa-icons: (
  "wheat": $fa-var-wheat,
)
```

**Comment by robmadole** [comment]
Yep, I get that. The confusing part is that the warning indicates that the quoting should happen in the context of where the variable is used instead of where it's defined. My interpretation of this was that the loop was causing `$name` to be interpreted as a `SassColor` as I was not aware that a map (where the root definition is) needs to be quoted. (This is counter-intuitive as a library author) And performing the `'"" + $name'` gymnastics feels clunky. Thanks for taking the time to walk me through this.

**Comment by stof** [comment]
well, a map does not *need* to be quoted. It depends what you want. At the time the map is defined, Sass cannot guess whether you intended to use a string or a color as the key (as I said, using color is valid, even though it may not be common).

At the time Sass sees a SassColor used in interpolation, it warns you about that being unexpected, but there is no way for it to track down where the value was originally defined (or at least not reliably and not all the time).
