### ISSUE TITLE
importer functions not executing for @import, @use etc

### ISSUE THREAD

**Issue by pete-hotchkiss** [sass/dart-sass#1260]
using `sass: 1.32.8` and `node: 14.5.5` 

previously in `node-sass` I would expect something like the below

```
const sass = require("sass");

sass.render({
  data: `@import "entry";`
  includePaths: [...paths],
  importer: function(u, p, d) {
    console.log("url", u)
  } 
},
(e, result) => {
   console.log(result.css.toString());
})
```

Given 

```entry.css
@import "a";
$foo: 24px
```

```a.scss
$bar: #339966;
```

When run to have output to the console both 
```
url entry.css
url a.scss
```

however now - it **only** runs once - for `entry.scss`, I dont see the console log for the second file

_however_ the `result.stats.includedFiles` does include "a.sass" in the collection - it's just the importer never runs for it.

**Comment by pete-hotchkiss** [comment]
I've whipped up a quick repos with examples of both `node-sass` and `sass`

https://github.com/pete-hotchkiss/dart-sass-importer-issues

**Comment by stof** [comment]
the behavior of dart-sass is to try a relative import first and then to check the importers (first the `option.importer` callbacks and then the include paths).

**Comment by pete-hotchkiss** [comment]
thanks for the clarification @stof. Is there no way to force the `option.importer` callback to be fired then.

If it helps - my context is one where I was previously (in `node-sass`) intercepting the contents of each `.scss` file and extracting information from it for an aggregated analysis of variables etc. 

So having the ability to read the stream of each unique file as `sass` moved through the imports meant I could get what I needed.

**Comment by stof** [comment]
The importer callback is not a hook guaranteed to be called for each imported file. It is a callback to customize the resolution of files not found relatively (by returning a path for them)

**Comment by pete-hotchkiss** [comment]
understand - but this is a significant behavior change between `node-sass` and `sass` so I'm trying to understand the content of the change and the benefits of it.

**Comment by stof** [comment]
Well, you usage was never intended to be supported by node-sass either, AFAICT: https://github.com/sass/node-sass#importer--v200---experimental

**Comment by Awjin** [comment]
@pete-hotchkiss Sorry for the frustration here, but it looks like you have an acceptable workaround. In general, Dart Sass is the reference implementation, so discrepancies between it and Node Sass should be considered not as "changes that Dart Sass made", but as divergent behavior on Node Sass's end. Since Node Sass is deprecated, parts of it may remain experimental and buggy moving forward.

**Comment by stof** [comment]
@pete-hotchkiss the documentation of the Sass language is also saying that imports are resolved first as relative paths, and go through the load path feature of the compiler implementation: https://sass-lang.com/documentation/at-rules/import#load-paths
The fact that libsass reversed the order for its experimental feature is an issue of libsass (and so node-sass)

**Comment by pete-hotchkiss** [comment]
all good - this has given me the clarification and a better understanding - really appreciate both of your time on this

**Comment by duzun** [comment]
I understand the logic behind this behavior, but can't find a solution to my case.
I intercept the `@import` of CSS files to update the `url(<path>)` with `postcss-url` according to the CSS file's location and the SASS file importing it.
I want to move from `node-sass` to `sass`, but because of this behavior change I'm stuck with `node-sass` for now :(
I also have a `url()` function that deals with rewriting for SASS files, but it doesn't seem to be invoked for a CSS file. Any suggestions on how to handle `url()` rewrites for imported CSS files?

**Comment by joneff** [comment]
@Awjin three are other reasons why bringing back importers can be (and is) a good thing:

**Speeding up**

Test case: `npm i @progress/kendo-theme-default` and build `scss/all.scss` with node-sass and dart-sass.

Bit of context: I am a developer working on Kendo UI (ui components), more specifically, I work on the theming part. By design, regardless how wrong it is, our component files are "linked" or "depend upon each other". For example, the toolbar component depends on the button component so developers can only include `scss/toolbar/index` and still get the styles for the button.

It does happen that certain files are imported more than once. That leads to about ... 77 k imports in the default theme and even more so in the derived themes. The compilation, understandingly, takes a lot of time:

* node-sass: 41.026 s
* dart-sass: 78.989 s

Interestingly enough, dart-sass reports just a couple of hundred files in `includedFiles`, where as node-sass the full 77 k. That doesn't help though... I guess the files are still processed...

Here is where loaders come in: with node-sass and importer (that caches files and returns empty files for processing), I can bring the total time to a second per theme. I can't do the same for dart-sass, though:

* node-sass: 0.622 s
* dart-sass: 78.627 s

Lastly, the behaviour of the importer is not consistent: in dart-sass, it will skip the call for a existing `.scss` file, but will trigger the call for a existing `.json` file. Obviously, not the case with node-sass.

**Comment by nex3** [comment]
@duzun https://github.com/sass/sass/issues/2535 is tracking support for custom `url()` handlers, which would cover that use-case.

@joneff For more context, internally Dart Sass caches the stylesheets at each given canonical URL. This is *usually* better: it means that you don't have to spend time reparsing the same file over and over again, and if the file somehow changes on the filesystem during compilation you won't get into a weird and inconsistent state. However, it does break with import-once importers, because those importers are essentially a big hack: they *intentionally* make it look like the files being imported change during compilation, by transforming into empty files after they've been loaded once.

The `@use` and `@forward` rules specifically exist to solve this issue, though. They *guarantee* that the given URL is only loaded once without needing importer hacks. If your project is spending 78 seconds doing nothing but reloading files, I recommend switching to the new module system as soon as possible.

**Comment by joneff** [comment]
@nex3 I understand any and all reasoning you may provide. That doesn't change the fact that currently I get 78 s in absolute terms and 120 x in relative terms better performance thanks to importers!

Humor me for a moment -- should I migrate to the new module system, would I get the same level of performance? Would I be able to compile my project in less than a second?

That question is very important, considering that the old `@import` syntax will become deprecated in dart-sass. That in terms means that the next time webpack gets updated with the new version, our framework will stop working.

Funny enough, just shy of two years ago this happened -- telerik/kendo-themes#722. With angular/angular-cli@ce15899, angular-cli updated to latest web pack, yada, yada, yada, bye, bye extending composite selectors yada, yada, yada, errors. And angular-cli@8 wasn't even official!

Apart from the google folks in the material themeing department, is there any other **large enough** project that you can think of that uses the module system?

**Comment by nex3** [comment]
> Humor me for a moment -- should I migrate to the new module system, would I get the same level of performance? Would I be able to compile my project in less than a second?

I can't answer that confidently without actually doing the conversion and measuring the results. That said, if 98% of the time in Node Sass was being spent re-running imports as your numbers suggest, I'd expect the same is roughly true for Dart Sass and so moving to the module system would result in a similar scale of improvement.

> Apart from the google folks in the material themeing department, is there any other large enough project that you can think of that uses the module system?

We don't really keep a database of major Sass users. I suggest asking around user groups to try to find the answer to this quesiton.
