### ISSUE TITLE
Policy regarding the minimum dart version and the supported dependencies

### ISSUE THREAD

**Issue by stof** [sass/dart-sass#1262]
Currently, the pubspec file reports compatibility with dart sdk >=2.6. but the CI only runs on the stable channel (i.e. 2.12 now). And in practice, it is impossible to run the CI on dart 2.6, because cli_pkg requires dart >=2.7 for instance.

The CI also runs only with the latest versions of the dependencies in the pubspec range (at least the latest one being compatible with the SDK and other constraints), which makes me ensure whether lowest bounds are actually realistic.

**Comment by nex3** [comment]
Generally speaking, the lower bound of a dependency (or SDK constraint) should be the lowest version possible that has all the features your package uses. We can safely rely on the version solver to know which *actual* versions are supported due to the constellation of transitive constraints, but we don't want to have to worry about that ourselves.
