### ISSUE TITLE
VM initialization failed?

### ISSUE THREAD

**Issue by mcglk** [sass/dart-sass#1268]
Out of the blue, I got "VM initialization failed: Wrong full snapshot version, expected '5b97292b25f0a715613b7a28e0734f77' found '8ee4ef7a67df9845fba331734198a953'" and sass doesn't run anymore.

**Comment by jathak** [comment]
What method did you use to install Sass? If you installed it through `pub`, this error is likely because you updated your Dart SDK and need to re-run `pub global activate` to build a snapshot that's compatible with that SDK.

If you installed through some other method, this sounds like a bug, but it's likely specific to the particular installation method you used.

**Comment by mcglk** [comment]
I downloaded it from the Sass website. It went from running-perfectly-fine to the error described above with no updates to the Dart SDK nor to the Sass snapshot.

That said, it turns out that my SSD drive started showing signs of corruption shortly afterwards, and I'm reinstalling the system as I speak, so it may be related to that. This hasn't been a fun few days, and I apologize if this winds up being a spurious error. I'll update later.

**Comment by stof** [comment]
@mcglk any news on that topic ?

**Comment by mcglk** [comment]
Yeah—basically, my SSD ate itself. It took a couple of weeks to recover on a new system. Since then, I've had no problem at all with Sass.
