### ISSUE TITLE
@import "theme.css" does not produce @import url(theme.css)

### ISSUE THREAD

**Issue by duzun** [sass/dart-sass#1284]
The [documentation](https://sass-lang.com/documentation/at-rules/import#plain-css-imports) states that 
`@import "theme.css";` ⇒ `@import url(theme.css);`

but it doesn't.

**Comment by Awjin** [comment]
This is a bit confusing, because the docs still use Ruby Sass to generate the example Sass/CSS. In this case, the output of Ruby Sass (`@import url(theme.css)`) does differ from that of Dart Sass (`import "themes.css"`). However, since the two statements are semantically equivalent, the syntactic difference shouldn't matter.

Generally speaking, to avoid similar issues, we should migrate the website to a static site generator that supports using Dart Sass. (See https://github.com/sass/sass-site/issues/519)

**Comment by duzun** [comment]
Even though there is no CSS syntactic difference between the two formats, there is a difference at the SASS level: `@import url(theme.css)` has a function call, but `@import "theme.css"` doesn't.

I have overwritten the `url()` function in `dart-sass` with `functions` options to be able to rewrite the assets' URLs.
With `node-sass` my setup was working perfectly up to node@15, then broke.

Actually I have two issues with the SASS `@import "theme.css"` now:
- it doesn't invoke `importer()`,
- it doesn't invoke `functions.url()`

Now I have to go over all the sources and update the syntax to `@import url(theme.css)` and also update the custom `url()` to handle includePaths search...
