### ISSUE TITLE
[Question] Shared library distribution

### ISSUE THREAD

**Issue by irundaia** [sass/dart-sass#1304]
Hi,

I've supported a package for a web framework that used libsass under the hood. 
However, now that libsass has been deprecated, I'm looking to swap it out for dart-sass. So I was looking for a way to compile dart-sass to a shared library (.so/.dll/.dylib) for loading into a java framework. 

Is this at all possible? I know that dart supports compiling to native executables, but that does not allow loading into another process unfortunately.

**Comment by jathak** [comment]
Dart doesn't support building a shared library, but we've developed an protobuf-based [embedded protocol](https://github.com/sass/embedded-protocol) that lets you communicate with an [embedded Sass compiler](https://github.com/sass/dart-sass-embedded) via stdio.

At the moment, we have a [Node-based host in beta](https://github.com/sass/embedded-host-node), but we don't have any current plans to write host libraries for other languages ourselves. If you're interested in writing an embedded host for Java, we could provide some advice and guidance.

Closing this since a shared library specifically isn't something we're likely to be able to support given the Dart SDK's lack of support.
