### ISSUE TITLE
Consider soliciting language proposal feedback via npm

### ISSUE THREAD

**Issue by Awjin** [sass/dart-sass#1397]
The [`/`-as-division deprecation proposal](https://github.com/sass/sass/blob/master/accepted/slash-separator.md) was merged in 2019 after going through the formal process of public review. The deprecation was [implemented recently](https://github.com/sass/dart-sass/pull/1306) in Dart Sass. Although this was just a deprecation and not a breaking change, it led to cases where developers saw their builds break due to too many deprecation warnings. Several such reports were filed here: https://github.com/sass/sass/issues/2565.

The most common developer frustrations seem to be:
1. Surprise that `/`-as-division was being deprecated in the first place.
2. `math.div()` not seeming like a good replacement for `/`.
3. The inability to control deprecation warnings flooding in from upstream dependencies.

(3) is an implementation detail which we fixed, but (1) and (2) seem like they could be communication problems. Even though the Sass team solicited feedback on the proposal as it normally does, developers don't necessarily follow Sass on its public channels and only discover these proposals when their build breaks—at which point the proposals have long been discussed and merged.

We should consider adding an npm `postinstall` script that solicits feedback on upcoming language feature proposals. This could help widen the funnel of Sass developers who are aware of and review proposals.

**Comment by nex3** [comment]
I got most of the way through implementing this before realizing it won't actually work: as of npm 7.x, postinstall scripts can't actually print any output to the user unless they explicitly pass a [`--foreground-scripts` option](https://docs.npmjs.com/cli/v7/using-npm/config#foreground-scripts), which we can safely assume essentially no one will pass. https://github.com/npm/cli/issues/3347 indicates that this is intentional on the part of npm, so unfortunately I think this issue is infeasible.

**Comment by Akxe** [comment]
Why does [the page that informs about this breaking change](https://sass-lang.com/documentation/breaking-changes/slash-div) does not have a poll to vote about the feelings of people that got there?

This change caught me off guard and I want to express my opinion before it is too late...
