### ISSUE TITLE
math.div paddings

### ISSUE THREAD

**Issue by untainsYD** [sass/dart-sass#1508]
Can you provide some padding between dividend and divisor?

First example:
**Input:**
```scss
@use "sass:math";

$var: 2;
$calc: calc(math.div(100%, $var));
@debug $calc;
```

**Output:** DEBUG: 50%.

---

Second example:
**Input:**
```scss
@use "sass:math";

$var: 2;
$calc: calc(math.div(100%, #{$var)});
@debug $calc;
```

**Output:** calc(100%/2).

The first example is fine, and it works well, but there is one problem in the second example (with interpolation). I want to see the output (in the second example) as `calc(100% / 2)`, but there are no paddings between dividend and divisor. And code becomes hardly readable. Maybe you can make some options for users to use `math.div` with paddings or without.

**Comment by stof** [comment]
You can simplify things a lot. Inside `calc()`, the `/` division operator is still allowed. You don't need to use `math.div` (and then, dart-sass will render the calc division with spaces around the operator in expanded mode as it will actually know that it is a calc division, not an unquoted string containing `100%/2` as produced by dividing strings). In compressed mode, there will still be no space though (as they are not needed in CSS around the division operator, and the compressed mode uses the more compact output).

**Comment by untainsYD** [comment]
Thank you for your answer, but if I would follow your advice with the `/` division operator, I will get warnings like that:
- **DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.**
- **Recommendation: math.div($value, $rem-baseline)**
- **More info and automated migrator: https://sass-lang.com/d/slash-div**
- `$result: append($result, $value / $rem-baseline * 1rem, $separator`

And can I use for development (in dev mode) spaces around the division operator for better readability? Is there some option for that? Maybe you would add some flag or attribute for sass compiler, idk.

**Comment by stof** [comment]
@untainsYD I said "Inside calc`. `$result: append($result, $value / $rem-baseline * 1rem, $separator` is not inside calc, and so my advice does not apply. `calc()` is treated in a special way, as it is about doing math, and so `/` is still the division operator there.

> And can I use for development (in dev mode) spaces around the division operator for better readability? Is there some option for that? Maybe you would add some flag or attribute for sass compiler, idk.

As said before, when the compiler outputs a calculation division, it already puts spaces around it in the output in expanded mode, for readability. However, `calc(math.div(100%, #{$var)})` is *not* about about doing a calculation division. It is dividing a number and **a string** (the result of the interpolation). And so this applies the `/` operator of strings, which concatenates strings with a `/` separator. Using `math.div` on strings rather than numbers is quite unexpected.

**Comment by jathak** [comment]
@stof's response here is correct. `math.div` supports concatenating strings for the time being to make it a drop-in replacement for the deprecated `/`-as-division, but should generally not be used in that way for new code.

Sass only provides limited control over the output format (`expanded` vs `compressed`). Since `calc(100%/2)` and `calc(100% / 2)` are equivalent, the current output is correct for your code (though you may prefer to just write `calc(100% / $var)` and your code and have it simplify to `50%`). If you want more control over your final CSS's format, consider using/writing a PostCSS plugin and passed the result of compiling your Sass code to that.
