### ISSUE TITLE
Import scss files via * pattern

### ISSUE THREAD

**Issue by zvitek** [sass/dart-sass#1519]
Hello,
In my project I use import scss files via `*` pattern. Is there any way to make this import work with this package?

```
@import "../components/**/*.scss";
```

Thank you for help.

**Comment by stof** [comment]
Seems like something that should be moved to https://github.com/sass/sass as it is about requesting a new feature in the languange.

**Comment by jathak** [comment]
This isn't something we'd add support for, as it would cause portability issues (since what gets imported would be dependent on what other files are present) and would prevent static analysis.

It would also violate many of the [goals of the module system](https://github.com/sass/sass/blob/main/accepted/module-system.md#goals), so we wouldn't add support for globs in `@use` or `@forward`, and since `@import` will eventually be deprecated, it doesn't make sense to add a new feature just for it.
