### ISSUE TITLE
beta.1 throws on /deep/ selector

### ISSUE THREAD

**Issue by daniel-v** [sass/dart-sass#154]
Angular 2 emulated view encapsulation gives special meaning to `/deep/` selector. This is true for TS and Dart versions as well. https://webdev.dartlang.org/angular/guide/component-styles#!#special-selectors

Expressions such as: 
```
:host /deep/ .expected-optional-class { }
````
is valid and is a [recommended](https://github.com/dart-lang/angular2/issues/405#issuecomment-303789004) way to deal with certain use-cases. Would be nice if dart-sass supported it.

**Comment by nschonni** [comment]
Related https://github.com/sass/sass/issues/2136

**Comment by nex3** [comment]
This is intentional. The `/deep/` syntax is not in any current CSS spec, nor has it been for some time. Its replacement, `>>>`, is [explicitly marked](https://drafts.csswg.org/css-scoping-1/#deep-combinator) as "invalid when used in stylesheets". Chrome support for `/deep/` in stylesheets ["being deprecated"](https://www.chromestatus.com/features/6750456638341120).

**Comment by zoechi** [comment]
This makes dart-sass unusable with Angular

**Comment by zoechi** [comment]
@matanlurey do you have any thoughts on this?

**Comment by matanlurey** [comment]
@nex3 and I have settled on using `::ng-deep` in AngularDart 4.x.

We can back-port and release `3.2.0` to make this available to AngularDart users sooner. Follow:

https://github.com/dart-lang/angular2/issues/454
