### ISSUE TITLE
node-sass to dart-sass: build time is off the charts.  from 8 seconds to 4 minutes. 

### ISSUE THREAD

**Issue by smchargue** [sass/dart-sass#1557]
I'm migrating my build from node-sass to dart-sass, mostly because I don't feel like I have a choices since I can't seem to get node-sass working on a new windows 10 enviornment.

After finally getting my gulp build task to run, it has gone from 8 seconds to build with node-sass to 4.77 minutes to build with dart-sass.

What in the hell have I done wrong?

**Comment by rmaenk** [comment]
Hello @smchargue , 

It seems that you run into  the same issue as me.
Dart Sass compiler, you use, is written in pure javascript. You need a standalone Dart Sass compiler (it is very fast), but it is cli. 
As alterantive you can try [sass-embedded](https://github.com/sass/embedded-host-node).
It works for me, but it is still in beta and some things may not work.
I am using it with gulp-sass (v5.0.0).

Hopes it help,
Regards,
Roman

**Comment by jathak** [comment]
While using the embedded compiler may indeed help here, 8 seconds on Node Sass -> 4 minutes on the JS compiled Dart Sass seems extreme. We do expect some slowdown from running on Node, but there may be some other issue that we can fix to improve this.

A couple things that could help debug this:

- are you using any custom importers or functions?
- how big is this project in terms of the amount of Sass code?
- are you doing anything complex with `@extend` or any other features that you suspect could be slowing things down?

**Comment by nex3** [comment]
If you can provide us with your stylesheets, that can be particularly helpful in tracking down why they're taking so long to compile.

**Comment by smchargue** [comment]
Hi, thanks to everyone for the reponses.  My style sheets are coming from the npm package @progress/kendo-theme-bootstrap@4.17.0;  I'm locked into that version for the short-term.  So, even if a later version had some "fixes" i couldn't implement them. 

I'm adding about 200 lines of custom scss to that along with a new _variables.scss file  - but for the most part, i'm using that "out of the box"; my custom work is pretty basic, because that is the current level of my sass skills. 

I've got the dart sass compiler working great for me, in fact along with a custom "watch" powershell script it works better for my build process than node.js/npm/gulp ever did.  my build time is 80% what it was in gulp/node-sass now.

**Comment by nex3** [comment]
After building `kendo-themes/packages/bootstrap/scss/all.scss` locally on my laptop in various ways, I'm pretty sure this is the same issue as #1534. If you're not already using the latest version of Dart Sass, make sure to update, because we've done some optimization on this sort of system However, the root of the issue is that the legacy Node API is simply not very cacheable, which makes projects like this with many many imports much slower than they need to be. Here are the relevant numbers I'm seeing:

* 1.2s with the native Dart Sass CLI
* 2.9s with the Node Sass CLI
* 1m with Dart Sass's legacy JS API using `renderSync()`
* 1m13s with Dart Sass's legacy JS API using `render()`
* 6.3s with Dart Sass's new JS API (not yet released)

This suggests a few potential ways forward for you, once you've upgraded to the latest Dart Sass:

* Use `renderSync()` rather than `render()` if you aren't already. This is probably a relatively easy change, but it won't give you a ton of extra performance.
* Wait until Dart Sass releases the new JS API (planned for early December) and use that. This won't require installing anything new, and will give you a very hefty speed boost.
* Wait until the embedded host releases, hopefully in Q1 2022, and use that. This will wrap a native Dart Sass executable in the new JS API and provide even more of a performance boost.
* Simply use the native Dart Sass CLI immediately. This is the biggest change relative to your current setup, but it'll give you a massive performance boost and requires no additional waiting on your part.
