### ISSUE TITLE
quiet-deps does not work when executing mixins from a dependency library

### ISSUE THREAD

**Issue by gavmck** [sass/dart-sass#1560]
Been trying to figure out why sass won't stop emitting `math.div` warnings for code coming from `@angular/material` all morning.

- We import `@angular/material/theming` which only contains mixins and sass variables.
- `node_modules` is in the load-path
- `@angular/material/theming` is detected correctly as a dependency
- We use the mixin `@include mat-core` and it throws `math.div` warnings

I've set up a minimal repo to demo the bug: https://github.com/gavmck/dart-sass-mixins-deps-bug

Thanks!

**Comment by gavmck** [comment]
Current workaround is to move the import and the mixin include to it's own file/folder then add that folder to the load-path so we can pretend the whole file is a dependency.

```scss
// Keeping this in here so we can specify it as a
// dependency in sass includePaths option so quiet-deps
// works, otherwise it thinks the mixin code is not a dep
// and throws warnings for math.div issues
@import '@angular/material/theming'; // only importing material core saves about 2000 lines of css...
@include mat-core; // this mostly just adds style to @angular/cdk elements
```

**Comment by stof** [comment]
the implementation of `quiet-deps` indeed seems to rely on the context of the currently evaluated file. When running an imported mixin, the evaluated file does not switch back to the source of the mixin (the code being evaluated comes from that other file, but the current context is still the place where we are executing `@include`).

@nex3 would it make sense for functions and mixins to be reported as dependencies based on their declaration rather than the place where they are called from initially ?

**Comment by nex3** [comment]
This is tricky, because we explicitly *do* want to emit warnings in this scenario when they're caused by the user's code. For example, if a mixin includes its own `@warn` rule that gets triggered when the user passes in some risky arguments, it's important that that warning is surfaced even if `--quiet-deps` is enabled. So it's not as simple as just turning off warnings for all mixins and functions defined in dependencies. That said, we could probably specifically silence *deprecation warnings* in this way.

**Comment by stof** [comment]
@nex3 for `@warn`, I think the filtering should be based on the caller of the function containing them maybe, instead of being based on their own location (which would be similar to how warnings work for compiler-defined functions where warnings inside the function are based on the caller of the function).
an alternative is indeed to limit it to deprecations.

**Comment by nex3** [comment]
Looking at the caller kind of has the same issue—either we only look at the *immediate* caller, in which case it breaks warnings that are factored out into multiple layers of internal mixins/functions, or we look at the *original* caller, which is likely to usually be in user code. So I think limiting it to deprecations makes more sense.

**Comment by KimBum** [comment]
Bumping this as this is an ongoing issue, which causes a really long output for global style compilation with Angular.
Could silencing deprecation warning this way still be an option?
At least in our case we do make heavy use of mixins for theming, so not sure, if that would hide deprecation warnings from our own code.
