### ISSUE TITLE
Unexpected behavior for str-insert with negative index

### ISSUE THREAD

**Issue by cleydyr** [sass/dart-sass#1568]
Input
```
str-insert("abcdefghijklmn", " ABCD ", -28);
```

Expected ouptut (libsass v3.5.5):
```
" ABCD abcdefghijklmn"
```

Expected ouptut (Ruby Sass v3.7.4):
```
" ABCD abcdefghijklmn"
```

Current output (Sass Version: 1.44.0)
```
"ab ABCD cdefghijklmn"
```

**Comment by stof** [comment]
This is caused by this code: https://github.com/sass/dart-sass/blob/a32000ea9af30ad443a9e1847f09ec1070d82f36/lib/src/functions/string.dart#L62-L72

When the negative index is bigger (in absolute value) than twice the string length, `indexInt` will still be negative after adding the string length, and `_codepointForIndex` will add the string length again.
