### ISSUE TITLE
ts types is broken in v1.45.0

### ISSUE THREAD

**Issue by xuchaobei** [sass/dart-sass#1571]
in v1.45.0, the ts type declaration for `Options` is:
```
export interface Options<sync extends 'sync' | 'async'> {
  //...
}
```  

while in v1.43 is: 
```
export interface Options {
  //...
}
```

**Comment by nex3** [comment]
Sass didn't include type declarations prior to 1.45.0. There were unofficial user-submitted declarations in DefinitelyTyped, but since they were neither maintained by the Sass team nor distributed with the Dart Sass package, we decided to provide better typings rather than try to maintain backwards-compatibility with those ones.

If you want to use the old type definitions, you can add this to your `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "paths": {"sass": "node_modules/@types/sass"}
  }
}
```

although this will prevent you from using the new JavaScript API.
