### ISSUE TITLE
sass-map isn't a valid CSS value. worked in node-sass but not in dart-sass

### ISSUE THREAD

**Issue by interactivevalues** [sass/dart-sass#1577]
I moved from node-sass to dart-sass and one line breaks.
I got a simple map like
`$grid-breakpoints: (
    "xs": 0,
    "sm": 576px,
    "md": 768px,
    "lg": 992px,
    "xl": 1200px,
    "xxl": 1440px
);`

and I want to output this as content on a before like
`body.styleguide {
    &:before {
        content: "#{$grid-breakpoints}";
    }
}`

the error:
messageOriginal: ("xs": 0, "sm": 576px, "md": 768px, "lg": 992px, "xl": 1200px, "xxl": 1440px) isn't a valid CSS value.

Is this a bug in dart-sass or any idea what I could change?

cheers,

ToM

**Comment by nex3** [comment]
Allowing this was a bug in Node Sass. When you write `#{$variable}`, Sass converts the variable to its CSS value representation and includes that in a string. Since a map isn't a valid CSS value, it can't be converted this way and this fails. If you want to convert *any* Sass value to a string for debugging purposes, you should use the [`meta.inspect()`](https://sass-lang.com/documentation/modules/meta#inspect) function.
