### ISSUE TITLE
Relative URL resolution before canonicalization doesn't take into account the ~ prefix

### ISSUE THREAD

**Issue by glromeo** [sass/dart-sass#1581]
As you can see here:

![image](https://user-images.githubusercontent.com/160981/147250817-c90d0cdf-cf92-4eb3-bee3-81e6e723975d.png)

My importer receives a file url that's joined when it should have received just ~mathsass/dist/math

For sake of completeness I am using the new compileString (sync) and the entry point source is:
https://github.com/glromeo/esbuild-sass-plugin/blob/v2.x/test/issues/23/main.scss

I am not familiar with dart so I refrained from botching a PR

**Comment by stof** [comment]
A `~` prefix is not special in URLs.

The legacy JS API was *not* working with URLs for imports, which is precisely what allowed webpack (and then esbuild) to invent that `~` prefix to trigger their own importer.

**Comment by glromeo** [comment]
I see your point and I too would like to see the ~ just disappear in favour of bare URLs but the ecosystem is still using it.
I would have much preferred two parameters not really because of this issue but rather because having a baseurl and a relative url and letting the importer decide to join them or not would have given more flexibility but I guess it's too late to change the signature is it?

**Comment by stof** [comment]
Well, a custom importer should still receive the relative URL (once the compiler fails to find a file matching the URL relative to the current file with the URL you see in your debugger)

**Comment by nex3** [comment]
This behavior is intended. The importer API explicitly *doesn't* pass in separate base and relative URLs so that importers will always handle relative and absolute URLs the same way. If your importer doesn't recognize a URL that's passed to `canonicalize()` or can't find a URL that's passed to `load()`, it should simply return `null`. The API will then pass the *original* URL to each importer in `Options.importers`.
