### ISSUE TITLE
Webpack, darts sass and dev tools performance issue

### ISSUE THREAD

**Issue by MrLechu** [sass/dart-sass#1582]
Hello,
In my example project i'm using `webpack`, `sass (dart sass)`. I have 8 react components in separate folders. Every component have its own styles. In every sass file i'm `@use` rule to load base styles. When i'm inspecting e.g button in browser dev tools, i see many entries `_base.scss` (number of entries is equal to number of a components). With a few components there is relatively fast i can inspect styles for button component in dev tools,  but with 228 components browser need to eg. 3 seconds to refresh and show style for the button. 
![image](https://user-images.githubusercontent.com/282236/147356462-07cb3548-350c-4e69-b4e0-d4f3b39d0ff4.png)

**Comment by stof** [comment]
The issue in your case is that webpack triggers separate Sass compilation for each Sass file that you import from JS.
The `@use` Sass directive evaluates the module only once. But if you combine the output of 228 Sass compilation, you can still have 228 evaluation of that module in the combined output.

If you want to include the base style only once, you should have one Sass entrypoint in which you import other Sass modules using *Sass* features rather than *webpack* ones.
