### ISSUE TITLE
A selector is missing after compile

### ISSUE THREAD

**Issue by kna** [sass/dart-sass#1587]
If a placeholder has nested classes and they are duplicated partially, a selector is not exported.
It is exported with libsass. 

input:
```
.a {
    @extend %b
}

%b {
    .c, .d .c {
       border: none;
    }
}
```

output(libsass v3.5.5 on [sassmeister](https://www.sassmeister.com/)):
```
.a .c, .a .d .c {
  border: none;
}
```

output(dart-sass v1.32.12 on [sassmeister](https://www.sassmeister.com/), dart-sass cli v1.45.2):
```
.a .c {
  border: none;
}
```

**Comment by jathak** [comment]
`.a .c` is equivalent to `.a .c, .a .d .c`, since any element that matches `.a .d .c` would already be matched by `.a .c`.

Both are correct, but Dart Sass simplifies away the `.a .d .c` as an optimization.

**Comment by stof** [comment]
@jathak due to the usage of specificity in the CSS cascade, the CSS using those 2 selectors might not be equivalent though (`.a .c` has a lower specificity)

**Comment by jathak** [comment]
Oh, whoops, that's right. They're not literally equivalent. I've edited my response to rephrase.

However, when it comes to `@extend`, we follow [these laws](https://github.com/sass/sass/blob/main/spec/at-rules/extend.md#specificity), which only require the new selector to have specificity greater than or equal to the extender (`.a` in this case), so the optimization is still valid.

**Comment by stof** [comment]
@jathak but in that case, the `.d .c` is not in the part of the selector being extended, but in a different part of the ComplexSelector (and for which there is no ambiguity anyway, as it is about descendants of the placeholder).
So I still find this quite unexpected.

When the extendee is a selector list (and so it has *multiple* specificities, one per complex selector in it), shouldn't the first law be applied separately for each complex selector ?

**Comment by itchyny** [comment]
Not sure about the validity of the laws, but here's an example that might confuses users (making `.c` with red border inside `.e` but not inside `.d`).
```scss
.a {
  @extend %b;
}

%b {
  .e .c {
    border: solid 1px red;
  }

  .c, .d .c {
    border: solid 1px green;
  }
}
```

**Comment by nex3** [comment]
> When the extendee is a selector list (and so it has _multiple_ specificities, one per complex selector in it), shouldn't the first law be applied separately for each complex selector ?

The first law is irrelevant when the extendee contains placeholder selectors. The first selector for each complex selector *does* have equal specificity to the original selector—in this case, the first selectors are `%b .c` and `%b .d .c`. But those selectors also contain placeholders, so they're omitted from the final CSS regardless of whether they're preserved by `@extend` or not. The only selectors that are actually emitted are those that are subject to the second law.

> Not sure about the validity of the laws, but here's an example that might confuses users (making `.c` with red border inside `.e` but not inside `.d`).

The laws are in place for a good reason: we *can't* guarantee that the specificity will remain the same as the original extendee's specificity, because we're removing some parts of the original extendee and replacing them with the extender. The specificity laws are the best guardrails we've been able to outline that provide guarantees we know we'll be able to abide by in all cases. The only other alternatives would be to provide *no* guarantees (which we did prior to defining the laws and provided even more confusing output), or to avoid optimizing out any duplicate selectors with different specificity (which would lead to unexpected stylesheet bloat and potentially breaking style changes for existing users).
