### ISSUE TITLE
Embed source map with sass.compile

### ISSUE THREAD

**Issue by MauroPfister** [sass/dart-sass#1594]
Is there a way to embed source maps when using `sass.compile()`?

Until now I was using the following code to embed my source maps into the final css file:
```js
const sass = require('sass');

options = {
    file: 'src/assets/styles/main.scss',
    sourceMap: 'xyz',
    sourceMapEmbed: true
}

const css = sass.renderSync(options).css.toString();

// Eleventy (https://www.11ty.dev/) takes care of writing the css string to a file.
```

Since `renderSync` is deprecated I wanted to switch to `compile` but I could not find any option to embed the source map. I need the source map to be embedded because I am writing the output of `compile` to a file using Eleventy's javascript templates which only allow one output file as far as I understand. Does anyone have any advice?

Thanks a lot!

**Comment by Awjin** [comment]
The new API intentionally does not try to account for the myriad of sourceMap use cases; instead, it returns a sourceMap object directly. I'd recommended adding a build step that concatenates your compiled Sass code and the sourceMap into the format expected by Eleventy.

**Comment by bennypowers** [comment]
Eleventy doesn't care about sourcemaps - it just copies stuff into the _site directory. The source map format expected by 11th is: 'source maps', the kind that browsers read

It doesn't seem an unreasonable ask for a compiler to provide sourcemap support that goes beyond "parse the object yourself". Source maps exist so that compilers can do their thing without troubling end users over it, right?

Couldn't sass at the very least export some functions that take a CompileResult and a SourceMap and output files that developers can use on the web?

**Comment by nex3** [comment]
> It doesn't seem an unreasonable ask for a compiler to provide sourcemap support that goes beyond "parse the object yourself". Source maps exist so that compilers can do their thing without troubling end users over it, right?

If you use Sass's command-line API, it will serialize source maps for you because it knows where the CSS file and the map file are going to be written to disk and where that is relative to the source. Even then, those assumptions could easily be broken if the relative paths are changed when the file is served.

In the JS API, Sass doesn't know *anything* about what's going to happen to the CSS or source map strings it returns. Even simple cases like "I plan to write the CSS to path A and the source map to path B and they'll have the same relative paths to the source code on the server as they do locally" requires a lot of extra configuration information, and anything more complex than that requires even more. It doesn't make sense to add all that configuration to the Sass API when the operation of "write a source map that connects these files" is fundamentally language-independent anyway.

> Couldn't sass at the very least export some functions that take a CompileResult and a SourceMap and output files that developers can use on the web?

Nothing about these functions would be CSS-specific, so it seems like a better task for a dedicated source map package than for Sass.

**Comment by MauroPfister** [comment]
Thanks @Awjin and @nex3 for the clarifications.

In case other people are having the same problem, here my solution inspired by https://github.com/thlorenz/convert-source-map:

```js
const result = sass.compile(file, options)

const sm = JSON.stringify(result.sourceMap)
const smBase64 = (Buffer.from(sm, 'utf8') || '').toString('base64')
const smComment = '/*# sourceMappingURL=data:application/json;charset=utf-8;base64,' + smBase64 + ' */'

css = result.css.toString() + '\n'.repeat(2) + smComment
```
