### ISSUE TITLE
spaces are removed when var is used in calc()

### ISSUE THREAD

**Issue by posttoast** [sass/dart-sass#1630]
Since switching from node-sass to dart-sass, I have an issue with using a var inside a css calc function: all spaces are removed, which results in faulty CSS.

```
$foo = 100px;
$bar = 100vh - #{$foo};

.test {
  height: calc($bar);
}
```

This results in:

```
.test {
  height: calc(100vh-100px); // Notice the lack of spaces
}
```
What I'm expecting:

```
.test {
  height: calc(100vh - 100px);
}
```

When I do this, it does work:

```
$foo = 100px;
$bar = '100vh - #{$foo}'; // Added a quote

.test {
  height: calc($bar);
}
```

But is it supposed to work this way?

**Comment by posttoast** [comment]
I've been using @debug to try and figure out what is happening and discovered this has nothing to do with the calc() function but is purely related to the way DartSass handles vars in comparison with RubySass/LibSass.

Input:
```
$foo: 100vh - 100px;
@debug $foo;
```

Output RubySass:
`100vh - 100px`

Output DartSass
`100vh-100px`

When using additions, something else happens:

Input:
```
$foo: 100vh + 100px;
@debug $foo;
```

Output RubySass:
`100vh + 100px`

Output DartSass:
`100vh100px`

Is this expected behaviour? I couldn't find anything about it in the documentation.

**Comment by nex3** [comment]
This is part of https://github.com/sass/sass/issues/1778, which was introduced ages ago and was even implemented in Ruby Sass although it didn't end up fully released before Ruby Sass was discontinued. You can see that issue for the details, but the high-level summary is that it changed how interpolation works adjacent to operators such that `100vh - #{$foo}` is now equivalent to `100vh - string.unquote("#{$foo}")` rather than `string.unquote("100vh - #{$foo}")`.

It's not entirely clear what you're trying to do here without more context, but I recommend using [first-class calc](https://sass-lang.com/blog/request-for-comments-first-class-calc) rather than trying to construct precisely-formatted strings.

**Comment by posttoast** [comment]
Thanks @nex3 :) I am however a bit curious about how this relates to my second post:

```
$foo: 100vh - 100px;
@debug $foo;
```

Resulting in:

`100vh-100px`

Am I supposed to put quotes around the var's value? So like this?

```
$foo: '100vh - 100px';
@debug $foo;
```
