### ISSUE TITLE
Undefined variable when using function to get map

### ISSUE THREAD

**Issue by mtsweir** [sass/dart-sass#1669]
In my test setup I have:

```
// _palette.scss
$colors: (
    blue: #0000FF
);

// _mixin.scss
@function getColor( $color, $shade: 'base', $map : $colors ){
  // check color exists
  @if (map-has-key($map, $color)) {
    $value: map-get($map, unquote($color));
    // check if color or map
    @if type-of($value) == color {
      // return color
      @return $value;
    }
    // check shade of color exists
    @if (map-has-key($value, $shade)) {
      // return shade of color
      @return map-get($value, $shade);
    }
  } 
  // else do nothing
  @return null;
}

// _tokens.scss
$body: getColor(blue);
```

In my app.scss I have the following:
```
@use "./tokens" as *;
@use "./mixin" as *;

body { color: $body; }
```

In my _mixin.scss I have the following at the top
```
@use "./palette" as *;
```

In my test usage:

```
body { color: $body; }
```

the output I get is:

```
body {
  color: getColor(blue);
}
```

Is there something I'm doing wrong here?

**Comment by stof** [comment]
your function is named `get-color`, not `getColor`. So the `getColor` call is considered to be a called to a CSS function and compiled as is.
Also, `_tokens.scss` does not import your `_mixins` file and so cannot use its functions.

Btw, if you import your modules with a namespace instead of with `as *`, Sass will report an error about calling an undefined function instead of considering it as a CSS function (as namespaced calls are known to be Sass calls).

**Comment by mtsweir** [comment]
> Also, `_tokens.scss` does not import your `_mixins` file and so cannot use its functions.
> 
> Btw, if you import your modules with a namespace instead of with `as *`, Sass will report an error about calling an undefined function instead of considering it as a CSS function (as namespaced calls are known to be Sass calls).

Thanks for the reply, I updated the function to `getColor`, didn't realise I had a typo.

So the updated structure looks like this:

**_palette.scss**
```
$palette: (
	black: #121212,
	white: #ffffff,
);
```

**_mixin-colour.scss**
```
@use "./palette" as *;

@function getColor($color, $shade: 'base', $map: $palette) {
	// check colour exists
	@if (map-has-key($map, $color)) {
		$value: map-get($map, $color);

		// check if colour or map
		@if type-of($value) == color {
			// return colour
			@return $value;
		}

		// check shade of colour exists
		@if (map-has-key($value, $shade)) {
			// return shade of colour
			@return map-get($value, $shade);
		}

		@else {
			@error "Unrecognized shade '{$shade}' for color '{$color}'";
		}
	}

	// warn when colour is not found
	@else {
		@error "Unrecognized colour '{$color}'";
	}
}
```

**_tokens.scss**
```
// Colours
@use "./mixin-colour" as *;

// Canvas
$canvas-default: getColor(white);
```

**Output**
```
body {
	background-color: #fff;
}
```

In order to get this to work, I found that I had to also use:
- **palette** inside the **mixin-colour** partial
- **mixin-colour** inside the **tokens** partial

I hope that is clear enough to follow. Could this be improved?

**Comment by stof** [comment]
Well, you have to use the modules in the file that wants to use them. That's totally the expected behavior. That was one of the design goals for Sass modules (compared to `@import` where everything was in a single global scope so a file could implicitly depend on everything imported before it), because it allows to reason locally instead of having to reason on the whole project at once.

**Comment by jathak** [comment]
@stof is correct here, this is working as intended.
