### ISSUE TITLE
Using Dart-Sass with element-ui libraries has an icon garbled problem

### ISSUE THREAD

**Issue by JasonLonger** [sass/dart-sass#1705]
The Element-ui source code was developed using node-sass, but the project had requirements for Dart-Sass.
When running online, there will occasionally be garbled icon codes.
Although the solution is obtained by searching on the Internet: by using css-unicode-loader, the double-byte characters in the dart-sass compiled into css files are then converted back to the hexadecimal code.
But it is hoped that this problem will be solved at the root.

Technology stack：Vue、Element-ui、Dart-Sass

**Comment by nex3** [comment]
When Sass emits non-ASCII characters, it always emits either a `@charset` declaration or a UTF-8 byte-order mark which will force browsers to correctly interpret those characters as UTF-8. If those characters aren't being interpreted correctly by your browser, it's because some other tool is mangling your CSS by incorrectly discarding these indicators. I suggest tracking that tool down and filing a bug there.

**Comment by JasonLonger** [comment]
已收到,谢谢。
