### ISSUE TITLE
Calculated module variables loaded by `@use` generates errors

### ISSUE THREAD

**Issue by WinterSilence** [sass/dart-sass#1742]
For example, I try compile Bootstrap 5 [_variables.scss](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss) by NodeJS:
~~~js
const sass = require('sass')
const path = require('path')
const result = sass.compileString(
    '@use "sass:meta";@use "functions";@use "variables";@debug meta.module-variables("variables")',
    {loadPaths: [path.join(__dirname, '../scss')]}
)
console.log(result.css)
~~~
execution failed:
~~~
sass.Exception [Error]: ("primary": #0d6efd, "secondary": #6c757d, "success": #198754, "info": #0dcaf0, "warning": #ffc107, "danger": #dc3545, "light": #f8f9fa, "dark": #212529) isn't a valid CSS value.
   ╷
94 │ $theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value") !default;
   │                             ^^^^^^^^^^^^^
~~~
but when I creates SCSS file with importing:
`scss/vars.scss`:
~~~scss
@import "functions";
@import "variables";
~~~
then modified script work fine:
~~~js
const sass = require('sass')
const path = require('path')
const result = sass.compileString(
    '@use "sass:meta";@use "vars";@debug meta.module-variables("vars")',
    {loadPaths: [path.join(__dirname, '../scss')]}
)
console.log(result.css)
~~~
It's looks like dart-sass crutch/defect.

**Comment by Goodwine** [comment]
It is known that Bootstrap 5 has issues with Sass' module system (i.e. `@use`/`@forwards`)
Specifically because of scoping as mentioned in the [`@use` documentation page](https://sass-lang.com/documentation/at-rules/use#differences-from-import)

There are specific examples and details about it on this [css-tricks tutorial on `@use`](https://css-tricks.com/introducing-sass-modules/#aa-import-files-with-use)

IIUC this should be solved eventually on Bootstrap 6, but it is not yet released

**Comment by Goodwine** [comment]
Hm, sounds strangely familiar to [this stackoverflow issue from an older sass version](https://stackoverflow.com/questions/51484320/scss-compilation-is-throwing-a-syntax-error-isnt-a-valid-css-value)

Can you provide more details?
- which specific `sass` version you have in `package.json`
- Do you have exactly only these two files: `_functions.scss` and `_variables.scss` under `../sass`?
  - If yes, would you mind pointing exactly which Bootstrap 5 commit/tag/version for those files you have? the files at `HEAD` does not have `$theme-colors-rgb`, that one is under `_maps.scss`.

**Comment by WinterSilence** [comment]
@Goodwine 
> Bootstrap 5 commit/tag/version

ups... sorry, Bootstrap 5.1.3: [_variables.scss](https://github.com/twbs/bootstrap/blob/v5.1.3/scss/_variables.scss), "sass" package "^1.45.0".

**Comment by WinterSilence** [comment]
@Goodwine you can use next code to reproduce problem:

`_functions.scss`:
~~~scss
@function map-loop($map, $func, $args...) {
  $_map: ();

  @each $key, $value in $map {
    // allow to pass the $key and $value of the map as an function argument
    $_args: ();
    @each $arg in $args {
      $_args: append($_args, if($arg == "$key", $key, if($arg == "$value", $value, $arg)));
    }

    $_map: map-merge($_map, ($key: call(get-function($func), $_args...)));
  }

  @return $_map;
}
~~~
`_variables.scss`:
~~~scss
$blue: #0d6efd !default;
$primary: $blue !default;
$theme-colors: ("primary": $primary) !default;
$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value") !default;
~~~

**Comment by Goodwine** [comment]
Gotcha, thanks for the example, I can repro, I'll take a look at this this week

**Comment by Goodwine** [comment]
Ok just as I had mentioned, this is because Bootstrap is not compatible with Sass module system.
When you use `@import` you are not using modules anymore and that's why your example works.

You can learn more and in greater detail here - https://css-tricks.com/introducing-sass-modules/

But just to give you an idea, your code has 
```scss
// _variables.scss
$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value") !default;
```
but from the perspective of `_variables.scss` it doesn't know what `map-loop` is because it's not in-scope (that's how Sass modules work), so Sass assumes this must be a CSS native function and then it fails because the variable `$theme-colors` is not a valid CSS value (because it's a Sass map)

You have to add `@use 'functions'` to make it work, but modules are namespaced by default so you need to either use the namespace...

```scss
// _variables.scss
@use 'functions';

$theme-colors-rgb: functions.map-loop($theme-colors, functions.to-rgb, "$value") !default;
```
... or remove the namespace with `as *`
```scss
// _variables.scss 
@use 'functions' as *;

$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value") !default;
```

For further assistance you can use community-supported forums such as [StackOverflow](https://stackoverflow.com/questions/tagged/sass)

**Comment by WinterSilence** [comment]
@Goodwine thanks for help!
