### ISSUE TITLE
Not recognizing nested classes inside :global after migrating from node-sass 4.14.0 to sass 1.49.9

### ISSUE THREAD

**Issue by misraelson** [sass/dart-sass#1782]
.accountMenu {
  height: 100%;

  &:global(.dropdown) {
    height: 100%;

    &:global(.open) {
      :global(.dropdown-toggle) {
        background-color: #f0f0f0;
        box-shadow: none;
      }
    }

    // &-toggle {   // used to be like this, now it doesn't work
    :global(.dropdown-toggle) {   // needs to be like this
      display: flex;
Recently updated a large project from "node-sass": "^4.14.0" to "sass": "^1.49.9"
There are several places in the code where we have something like:
.localParent {
    &:global(.someBootstrapComponent) {
         &-specifyer {
However this pattern is now giving an error:

SassError: Invalid parent selector ":global(.dropdown)"
24 │     &-toggle { // used to be like this

Any idea why this is happening and is there a way to have the 'old' syntax work?

**Comment by Goodwine** [comment]
The code samples from above aren't using the Markdown code formatting features correctly and the syntax is incomplete because your code is not terminated.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

I believe you are you trying to say this example should work?
```scss
.parent {
  &:global(.something) {
    &-other-thing {
      a: 1px;
    }
  }
}
```

If so, this code would not work because Sass would attempt to generate a CSS rule for `.parent:global(.something)-other-thing` which is not a valid CSS selector and node-sass was incorrectly allowing this invalid CSS selector to be generated.

You will need to refactor your styles so as not to rely on this bug. Sass itself does not support `css-modules` and `webpack` features.
