### ISSUE TITLE
Compressor Should Ignore Private-Use Unicode Ranges

### ISSUE THREAD

**Issue by bdkjones** [sass/dart-sass#1835]
Consider this CSS:

```
.fa-spinner:before {
    content: "\f110"; 
}
```

Compiling this with the `compact` or `compressed` output style results in this:

```
.fa-spinner:before{content:""}
```

Because the code point `\f110` falls into the "private use; reserved" range, the CSS compressor substitutes a "missing glyph" symbol. It's not visible on GitHub, but it looks like this in an IDE:

<img width="358" alt="Screenshot 2022-12-05 at 17 37 47" src="https://user-images.githubusercontent.com/926566/205787264-c25e2c51-acbc-44c7-81f8-fafdd11bfc6f.png">

## Why This Matters

For better or worse, libraries like Font Awesome are using the private-use Unicode range to let users put custom icons in their CSS. (Font Awesome translates the code point into an icon.) Dart Sass's compressor currently breaks this. 

It's not just Dart Sass—every CSS compression tool I can find behaves the same way.

## Proposed Solution

The CSS compressor should ignore any code points that fall into the "private use; reserved" range so that they are carried through as-is rather than replaced with the "missing glyph" symbol. This better matches the intent of the private-use range, where anything goes—there are, by definition, no defined glyphs that can be substituted for the code point.

**Comment by bdkjones** [comment]
@Goodwine the issue is the replacement of the string literal "\f110" with the glyph. That breaks in the browser--the Font Awesome icons aren't properly substituted and therefore aren't rendered on the page. The Font Awesome library is looking for that string literal.

This is NOT an issue when the Output Style is set to Expanded, since the compressor does not perform the glyph replacement and the string literal "\f110" appears in the CSS as-is.

My suggestion is that when the string literal is a Unicode code point that falls into the private range, the literal should be left as-is, just as if the Output Style were set to Expanded.

I don't really have a dog in the fight, I'm just tired of people emailing me to complain about Sass breaking their websites and blaming me for the problem.

**Comment by bdkjones** [comment]
@goodwine we might be getting hung up on terminology, but if you process that snippet of CSS using Dart Sass with Expanded and then Compressed output styles, you'll find that the output is indeed different--Expanded will open in an IDE (and the browser) with the ASCII string literal in place. The compressed output will not. I understand that the *character* in the compressed output has the correct code-point, but my suggestion is that there should be 5 ASCII characters in the output: `[\, f, 1, 1, 0]` instead of the single Unicode glyph associated with that code point.

**Comment by nex3** [comment]
Can you provide a reproduction where rendering is broken in an actual browser?

For additional context: when Sass encounters a non-ASCII character (whether it was originally written as an escape sequence or as a literal character), it will emit that character as the literal character in compressed mode (because that's shorter) and add a UTF-8 byte-order mark at the beginning of the document. The [CSS spec mandates](https://drafts.csswg.org/css-syntax-3/#input-byte-stream) that a byte stream beginning with a UTF-8 byte-order mark is _always_ decoded as UTF-8 even if the server is incorrectly configured, and if it's decoded as UTF-8 the literal character is semantically identical to the escape sequence. The only case where this might fail is if some post-processing step strips the UTF-8 BOM—but that's a bug in the post-processor, not in Sass.

We've heard about issues like this periodically for years, but in all that time we haven't seen a single working reproduction. I believe this is because all of those cases were caused by other (broken) tools incorrectly processing the CSS after Sass generated it. sass/dart-sass#568 tracks the addition of an option to generate ASCII-only output to help work around those broken tools, and if this is a major issue for you you're encouraged to help contribute a fix there. But ultimately, Sass is working as intended here.

**Comment by bdkjones** [comment]
@nex3 Sorry, I missed your response back in December. That explanation makes sense. The trouble is that fontawesome (and similar libraries) don't look for the actual unicode character. Instead, they're scanning the page for the literal sequence of ASCII characters: `\f110` and then dynamically replacing those characters with whatever icon has been assigned by the fontawesome people.

It's not that Sass is doing anything "wrong". It's that folks who want to use both compressed output *and* fontawesome can't do so because Sass won't carry the escape sequence through the compressor.

Because the private Unicode range has no assigned glyphs *by definition*, that means a browser won't render anything for the literal character that Sass outputs in compressed mode anyway. There is nothing to render. Because of that, my suggestion was: if someone uses the private Unicode range in a Sass file, the compressor should carry through the exact *way* they used the private range. If they supplied the literal character, bring that through. But if they supplied the escape sequence (`\f110`), bring *that* through instead and assume they had a good reason for expressing the character that way. This neatly solves the issue.

**Comment by bdkjones** [comment]
Fair enough! It's not my issue; I just deal with the angry support emails.

I do agree that the ideal solution is to have fontawesome recognize both strings. Unicode is hard.
