### ISSUE TITLE
Distribute native dart sass as npm package

### ISSUE THREAD

**Issue by 7rulnik** [sass/dart-sass#1889]
It would be nice to have the option to install and manage native dart sass like a normal node.js dependency via npm/yarn/pnpm.
Currently, it's possible to download it and adjust path variable or install it using brew, but with these options, it's hard to sync and manage versions in teams with different people.

I guess we can make something like esbuild doing here https://github.com/evanw/esbuild/blob/main/lib/npm/node-install.ts
Or like swc https://github.com/swc-project/swc/blob/main/postinstall.js

**Comment by nex3** [comment]
If you're already using Node, why not use the Node.js API? The `sass-embedded` package already uses the Dart VM, so if you need speed that's a good option.

**Comment by 7rulnik** [comment]
@nex3 I want to use it via CLI. As I understand there is no option for it in sass-embedded

**Comment by nex3** [comment]
This is something we're open to including as part of Embedded Dart Sass and the Node.js embedded host, although we're unlikely to have bandwidth to work on it ourselves. Here's what would need to happen for this to work:

* We'd need to expose the CLI `main()` method through the `sass_api` package entrypoint.
* We'd need to provide a flag on the Embedded Dart Sass executable (`--cli` maybe) to make it run in CLI mode instead of as an embedded compiler.
* We'd need to add an executable to the `sass-embedded` package that invokes this CLI.

**Comment by ntkme** [comment]
We can upload dart-sass binary just like the `optionalDependencies` of dart-sass-embedded, and then have a "dart-sass" npm meta package which only declares the `optionalDependencies`. This would allow us to provide a dart-only package without any JS API support, which I think it what this issue is asking for.

**Comment by 7rulnik** [comment]
And naive wrapper implementation could be like this:

```js
#!/usr/bin/env node

const path = require('path')
const foo = require.resolve(`sass-embedded-${process.platform}-${process.arch}/package.json`)
const pathToBinary =  path.resolve(foo, '../binary/sass')

require('child_process').execFileSync(
  pathToBinary,
  process.argv.slice(2),
  { stdio: 'inherit' },
);
```

But I think that main problem here — release process. At least for me, because I don't famillar with dart at all

**Comment by nex3** [comment]
I suggested including the CLI in `sass-embedded` because I'd like to avoid having two separate sets of npm packages that both bundle the compiled Dart version of Dart Sass for slightly different use-cases. I know it's more complicated to get the executable running in `sass-embedded`, but from a user's perspective it's much simpler to have two options, `sass` or `sass-embedded`, where the distinction between the two is always "one is pure JS and the other is the Dart VM".

**Comment by ntkme** [comment]
What about we merge dart-sass and dart-sass-embedded into one binary?

E.g. `sass` cli works as before and `sass --embedded` starts embedded compiler.

**Comment by nex3** [comment]
We're on board with the idea of folding the Dart embedded compiler into the Dart Sass executable. We'll need to be careful to ensure that it doesn't bloat the JS code size, but that should be feasible. I'll start taking a look at merging the repos.
