### ISSUE TITLE
SASS Dart is breaking React scripts node build

### ISSUE THREAD

**Issue by bard-hobson** [sass/dart-sass#1910]
Getting the below issue now out of nowhere when trying to push to heroku. Worked fine 5 days ago and all I updated was adding a new image to my images folder. I did not update any scripts or anything. I checked the node_modules and that file doesnt even have the line its mentioning below. Cannot find anything online speaking to it.

*******************
remote:        Creating an optimized production build...
remote:        Failed to compile.
remote:
remote:        ./src/sass/main.scss
remote:        /tmp/build_069a9000/client/node_modules/sass/sass.dart.js:19
remote:        self.exports = _cliPkgExportParam ?? exports;
remote:                                           ^
remote:
remote:        SyntaxError: Unexpected token '?'
************************

**Comment by ntkme** [comment]
Duplicate of #1909. Node <14 is already end of life and the support has been dropped. Make sure you update your node to a supported version.

**Comment by bard-hobson** [comment]
Thanks! That ended up being a big part of it and helped get it in the right direction. Moving from NPM to using yarn was the rest of the issue.

**Comment by jathak** [comment]
We inadvertently started using JS features that were unsupported in Node 12 without declaring we were dropping support  in our package.json. We've now published a new version (1.59.3) that should be compatible with Node 12 again.

While we do plan to drop support for Node 12 soon, since it's EOL, we shouldn't have done so without updating the package.json, and we're sorry for the trouble.
