### ISSUE TITLE
Import failure with `sass.compile()`, `sassEmbedded.renderSync()` and `sassEmbedded.compile()` methods, but not with `sass.renderSync()` method

### ISSUE THREAD

**Issue by Elysiome** [sass/dart-sass#1920]
# Introduction

Hi,

I create this issue on @nex3 [request](https://github.com/sass/dart-sass/issues/1913#issuecomment-1476966052).

The issue is simple to understand, there is an import failure with `sass.compile()`, `sassEmbedded.renderSync()` and `sassEmbedded.compile()` methods, but not with `sass.renderSync()` method:

```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException( 
                              ^

sass.Exception [Error]: Can't find stylesheet to import.
  ╷
5 │ @import "node_modules/bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\select2-bootstrap-5-theme\src\select2-bootstrap-5-theme.scss 5:9  @import
  style.scss 2:9                                                                 root stylesheet
    at Object.wrapException (C:\sass_import_failure\node_modules\sass\sass.dart.js:1237:17)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$4$baseUrl$forImport (C:\sass_import_failure\node_modules\sass\sass.dart.js:82636:19)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$3$forImport (C:\sass_import_failure\node_modules\sass\sass.dart.js:82665:19)
    at _EvaluateVisitor__visitDynamicImport_closure1.call$0 (C:\sass_import_failure\node_modules\sass\sass.dart.js:84417:21)
    at _EvaluateVisitor1._evaluate0$_withStackFrame$1$3 (C:\sass_import_failure\node_modules\sass\sass.dart.js:83672:25)
    at _EvaluateVisitor1._evaluate0$_withStackFrame$3 (C:\sass_import_failure\node_modules\sass\sass.dart.js:83678:19)
    at _EvaluateVisitor1._evaluate0$_visitDynamicImport$1 (C:\sass_import_failure\node_modules\sass\sass.dart.js:82598:19)
    at _EvaluateVisitor1.visitImportRule$1 (C:\sass_import_failure\node_modules\sass\sass.dart.js:82572:17)
    at ImportRule0.accept$1$1 (C:\sass_import_failure\node_modules\sass\sass.dart.js:87634:22)
    at ImportRule0.accept$1 (C:\sass_import_failure\node_modules\sass\sass.dart.js:87637:19)

Node.js v18.14.2
```

Summary table:
|                       Sass package and version                        |     Method     | Expected behavior (no import failure) |
| :-------------------------------------------------------------------: | :------------: | :-----------------------------------: |
|          [`sass@1.59.3`](https://www.npmjs.com/package/sass)          | `renderSync()` |                  ✔️                   |
|          [`sass@1.59.3`](https://www.npmjs.com/package/sass)          |  `compile()`   |                  ❌                   |
| [`sass-embedded@1.59.3`](https://www.npmjs.com/package/sass-embedded) | `renderSync()` |                  ❌                   |
| [`sass-embedded@1.59.3`](https://www.npmjs.com/package/sass-embedded) |  `compile()`   |                  ❌                   |

# Reproducible scenario

`package.json`:
```json
{
	"type": "module",
	"dependencies": {
		"sass": "^1.59.3",
		"sass-embedded": "^1.59.3",
		"select2": "^4.1.0-rc.0",
		"select2-bootstrap-5-theme": "^1.3.0"
	}
}
```

`style.scss`:
```scss
@import './node_modules/select2/src/scss/core';
@import './node_modules/select2-bootstrap-5-theme/src/select2-bootstrap-5-theme';
```

`index.js`:
```js
import sass from 'sass';
import sassEmbedded from 'sass-embedded';

const src = './style.scss';

sass.renderSync({file: src}); // ✔️ OK
sass.compile(src); // ❌ ISSUE
sassEmbedded.renderSync({file: src}); // ❌ ISSUE
sassEmbedded.compile(src); // ❌ ISSUE
```

# Context

Related comment:
- https://github.com/sass/dart-sass/issues/1913#issuecomment-1469049814 

Node.js version: `18.14.2`

**Comment by ntkme** [comment]
I think the failure may be the expected behavior here. In you example it is `node_modules/select2-bootstrap-5-theme/src/select2-bootstrap-5-theme.scss` trying to load `node_modules/bootstrap/scss/functions`.

1. The import should not be resolved relatively, as `node_modules/select2-bootstrap-5-theme/src/node_modules/bootstrap/scss/_functions.scss` need to exists. Obviously, this won't exist simply due to where npm installs packages, that we can rule out this case.
2. The current working directory is in `loadPath` by default in new API, so that it is expected to fail in new API.
3. The current working directory is in `loadPath` by default in the legacy API. However, it turns out there is a special logic in `NodeImporter` to always allow relative resolve from the working directory. It was not good idea as it introduces inconsistency of outcome depends on where the sass command is running. `sass-embedded`'s legacy API emulation does not have this logic and that's probably where the difference comes from:

https://github.com/sass/dart-sass/blob/09a5f09638b3d7a57f55907abcab624f98629d81/lib/src/importer/legacy_node/implementation.dart#L148-L156

We can change the behavior of legacy API in `sass-embedded` to align with `sass`, but we will likely not change the behavior in new API.

@nex3 Any thoughts?

**Comment by nex3** [comment]
Thanks for rooting this out, @Elysiome and @ntkme. In this case, we can't accurately emulate this behavior in the embedded host because the embedded host builds its legacy API support on top of the new API and the new API (by design) doesn't make it possible to distinguish between absolute and relative imports. I'm afraid this is one of the few cases where there's an unavoidable behavior difference between the two.
