### ISSUE TITLE
Javascript API: Upgrading to 1.63 breaks my VS Code extension

### ISSUE THREAD

**Issue by glenn2223** [sass/dart-sass#2032]
Hey!

I'm the maintainer of the VS Code extension [Live SASS Compiler](https://marketplace.visualstudio.com/items?itemName=glenn2223.live-sass). I'm attempting to upgrade to the latest version of SASS but compilation fails with the below error (which is specific to my rollup bundling I know - but hopefully the name means something)

```
Cannot read properties of undefined (reading 'readdirSync$1')
```
Here is the calling error line: (this is not the EXECUTING line - notice the `$x` suffix in the image)
![image](https://github.com/sass/dart-sass/assets/33450392/ff4b55ad-473c-4a9c-9438-a4deb4b771df)

Which fails because `self.fs` is `undefined`:
![image](https://github.com/sass/dart-sass/assets/33450392/c9d4dd00-73b5-49a0-8cc3-74081b98ddd9)

As `fs` is missing from here:
![image](https://github.com/sass/dart-sass/assets/33450392/c7fa3273-8c2c-4aa2-bd62-d9ebceb92691)

**Side bar**, `util` is missing in this one
![image](https://github.com/sass/dart-sass/assets/33450392/94fbc227-5745-486d-953f-4f7e3ce4f80e)

### V 1.62.1
But with `v1.62.1` you can see the same call stack:
![image](https://github.com/sass/dart-sass/assets/33450392/9db74f6a-f27d-418d-a171-78be89304b84)

Which doesn't fail because `self.fs` is **NOT** `undefined`:
![image](https://github.com/sass/dart-sass/assets/33450392/48c9e53b-6d24-449c-b2b1-decd48f77f56)

As `fs` **IS** passed here:
![image](https://github.com/sass/dart-sass/assets/33450392/277611bf-dd2d-46ed-b2b7-5c55e006ddfd)

**Back to that sidebar** - util is present here
![image](https://github.com/sass/dart-sass/assets/33450392/90a9b783-d43b-4b95-b8e4-862703cfb4ee)

---

I hope this helps. I can do my best to create a minimal repo if required.

I also flicked between the 2 versions as I was taking these screenshots. Meaning the only thing that changed is the version of SASS

**Comment by nex3** [comment]
The immediate cause of this is almost certainly because of how we restructured the package to add browser support. It suggests that your environment is loading npm packages in an unusual way.

In 1.63, we expose different entrypoints to different contexts:

```json
{
  "exports": {
    "types": "./types/index.d.ts",
    "node": { "require": "./sass.node.js", "default": "./sass.node.mjs" },
    "default": {"require": "./sass.default.cjs", "default": "./sass.default.js"}
  }
}
```

The `node` entrypoints load Node-specific libraries like `fs`, while the `default` entrypoints only load libraries that are platform-agnostic and so can run in the browser.

Your environment, though, isn't really playing by the rules. It looks like it implements a bunch of Node.js APIs, like the `process` API we use to detect if we're running under Node and the `fs` library we use to access the filesystem, but it doesn't load the `"node"` entrypoints as defined in package.json. This puts Sass in a weird state where it can't actually access the filesystem, but it still thinks it's running under Node so it won't give you useful error messages about it.

You've got a few options here:

1. If you don't actually _need_ filesystem access, you can just use `compileString()`.
2. You could try explicitly loading `sass.node.js` instead of `sass` to work around VS Code's weird rule breaking.
3. You could try to get VS Code to fix its behavior and load the `"node"` export, since it seems to support the Node APIs.

In any case, I don't think there's much we can do here other than maybe detect Node using the `fs` library instead of `process`.
