### ISSUE TITLE
@use pass configuration as a map variable

### ISSUE THREAD

**Issue by rwasef1830** [sass/dart-sass#2035]
Hello,
I want to load bootstrap scss with some variables overridden. So I got my variables in a _variables.scss

_variables.scss
```scss
$bootstrap-overrides: (
    primary: green
);
```

main.scss
```scss
@use "variables";
@use "lib/bootstrap/scss/bootstrap" with (variables.$bootstrap-overrides);
```

The compiler scolds me, I can't do that "syntax error".... I search and find that meta load-css function...
So I try again...

main.scss
```scss
@use "variables";
@include meta.load-css("lib/bootstrap/scss/bootstrap", variables.$bootstrap-overrides);
// I need to refer to bootstrap inside this file so I go ahead and use it, knowing that
// the include must come first because you can't configure a module except the first time it's loaded
// and that meta.load-css and use won't load modules loaded by each other multiple times.
@use "lib/bootstrap/scss/bootstrap";
```

I get scolded by the compiler again: "@use rules must be written before any rules"...

So how am I supposed to pass overrides from a map to a module being loaded ? Is there really no way except spell every variable out one by one again ? The problem is that I want to have this bootstrap loading part in a framework, so that in different projects I can pass different bootstrap variables to override....

I can't figure a solution to this problem... Is there any workaround ? I got very frustrated and angry feeling like I am boxed in blocked from very direction with seemingly arbitrary limitations with no way of escape...

Cross reference from a similar unanswered stackoverflow question:
https://stackoverflow.com/questions/69382592/how-to-use-scss-with-map-variable

**Comment by rwasef1830** [comment]
I tried making a _bootstrap-loader.scss file

_bootstrap-loader.scss
```scss
@use "sass:meta";
@use "variables";
@include meta.load-css("lib/bootstrap/scss/bootstrap", variables.$bootstrap-overrides);
```

Then in my main.scss
```scss
@use "bootstrap-loader";
@use "lib/bootstrap/scss/bootstrap";
```

I ended up with 2 complete copies of bootstrap in my CSS. It seems @use and the deduplication only happens in the same file ?
This is frustrating.

**Comment by nex3** [comment]
There's no way to pass a map as a configuration. You do indeed need to specify each variable individually.

> The problem is that I want to have this bootstrap loading part in a framework, so that in different projects I can pass different bootstrap variables to override....

Configurable variables work through `@forward`s, so if you just want bootstrap's existing variables to be configurable, you can just forward it and anyone who `@use`s your module will be able to configure it _through_ your module. For example:

```scss
// _wrapper-framework.scss
@forward 'bootstrap';

// Use bootstrap variables/mixins here.
```

```scss
// main.scss
@use 'wrapper-framework' with (
  $primary: green
);
```

> It seems `@use` and the deduplication only happens in the same file ?

When you `@include meta.load-css()`, it includes all the CSS in the loaded module _as though it were the body of a mixin_. This means that if you write multiple `meta.load-css()` calls, or you load the same module through `meta.load-css()` _and_ `@use`/`@forward`, you'll get multiple copies of the CSS.

**Comment by miss-programgamer** [comment]
If passing maps as configuration is not a planned feature, then how come the sass documentation recommends doing exactly that in [this paragraph](https://sass-lang.com/documentation/at-rules/use/#with-mixins)?

**Comment by nex3** [comment]
I think you may be misreading that documentation. It says:

> If you find yourself wanting to [...] pass [maps](https://sass-lang.com/documentation/values/maps) as configuration, [...] consider writing a mixin to set your variables instead and another mixin to inject your styles.

So it's specifically saying that if this is something you're trying to do, writing a mixin is better than using `@use ... with`.

**Comment by miss-programgamer** [comment]
Fair, I did misread that. However, how is the intended interpretation helpful? The example shown right after demonstrates usage of a library that was written with mixins in mind, but that's not actionable advice for users of libraries that weren't set up this way to begin with (such as the ever-popular bootstrap). Frankly, it's getting really frustrating trying to work with sass when so little consideration is given to the usage of older libraries when new features are added (and deprecated).

I think I'll just downgrade to a version of sass that doesn't yell at me for using `@import` and call it a day.

**Comment by nex3** [comment]
> Fair, I did misread that. However, how is the intended interpretation helpful? The example shown right after demonstrates usage of a library that was written with mixins in mind, but that's not actionable advice for users of libraries that weren't set up this way to begin with (such as the ever-popular bootstrap).

That advice is for library authors. If you're consuming an existing library, you'll have to follow whatever conventions it supports.

> Frankly, it's getting really frustrating trying to work with sass when so little consideration is given to the usage of older libraries when new features are added (and deprecated).

This is awfully harsh. What exactly do you want us to do here that we haven't done already? We made it totally clear that `@import` would eventually be going away (and why) from the moment we started working on the module system. When the module system launched we shouted from the rooftops that people should start planning to migrate to it. And we've pushed the timeline for it back again and again. We even reached out directly to major frameworks, including Bootstrap, offering free one-on-one assistance to migrate to `@use` in a backwards-compatible way.

The reality we ran into is that frameworks don't change unless there's active pressure to change them. If we waited to emit a deprecation warning until all the major frameworks had chosen to migrate themselves to `@use`, we'd be waiting forever, because in practice the deprecation warning is what prompted them to start the migration. And we can't wait forever because the existence of `@import` in the system is actively harmful to users at large, causing issues with performance, development complexity, and of course language complexity.

> I think I'll just downgrade to a version of sass that doesn't yell at me for using `@import` and call it a day.

If you just want to turn off the deprecation warnings, you don't need to downgrade. You can just pass `--silence-deprecation=import`. We made sure that option was available _before_ launching the deprecation because we didn't want to make life difficult for people like you who are still using frameworks that only support `@import`.
