### ISSUE TITLE
It's twice slower then node-sass

### ISSUE THREAD

**Issue by FDiskas** [sass/dart-sass#206]
Please check this simple example
[test.zip](https://github.com/sass/dart-sass/files/1578689/test.zip)
Reproduce:
1. `yarn`
1. `yarn dart`
1. `yarn node`

Or using NPM:
1. `npm install`
1. `npm run dart`
1. `npm run node`

Using `gnomon`
![https://i.imgur.com/nSAJo1L.png](https://i.imgur.com/nSAJo1L.png)

Or using `time`
![https://i.imgur.com/C7dXcif.png](https://i.imgur.com/C7dXcif.png)

**Comment by nex3** [comment]
We're aware of the performance differences; see [this file](https://github.com/sass/dart-sass/blob/master/perf.md) for benchmarks. It's also worth noting a few general things about performance:

* Node Sass is a wrapper for LibSass, which is written in C. Dart Sass (as distributed on NPM) is pure JavaScript. C is almost always going to be faster than pure JavaScript. Getting within 2-3x speed is pretty impressive, all things considered.

* Running Dart Sass from Dart will also always be faster than running it from JavaScript, because the Dart VM is faster than the JavaScript VM (for various reasons that are tangential to this discussion). You can try this yourself by downloading the Dart release from [the releases page](https://github.com/sass/dart-sass/releases).

* Our benchmarks have generally indicated that Dart Sass from Dart tends to be about the same speed or slightly faster than LibSass, due to algorithmic improvements. If speed is your primary concern and you don't need to define custom functions or importers in JavaScript, I'd recommend using that.

**Comment by halfnibble** [comment]
dart-sass finally supports all the features I am using with version 1.13.2. But my Sass/CSS build must be complicated because it takes about 46 seconds, or 6.5x longer. :(

**Comment by nex3** [comment]
@halfnibble If you can provide a stylesheet that's that much slower to compile in JS than it is in the Dart VM, that would be helpful for our optimization efforts.

**Comment by FDiskas** [comment]
As a comparison I prefer to use [bootstrap](https://getbootstrap.com/) as example.
