### ISSUE TITLE
FileSpan is not defined when using @warn with a custom logger.

### ISSUE THREAD

**Issue by Subash** [sass/dart-sass#2155]
I am using the `sass.compile` API with a custom logger, and it seems that `FileSpan` is not provided when using the `@warn` statement. I also checked with the `@debug` statement, and it appears that `FileSpan` is provided when the `@debug` statement is used with a custom logger.

I explored the source code for both statements and found some differences, but I couldn't figure out an elegant way to include `FileSpan` when calling `warn`.

[Link to the source for `@warn`](https://github.com/sass/dart-sass/blob/6205eac5d149b21154ca044ebfc0cd55631346d2/lib/src/visitor/evaluate.dart#L2237)
[Link to the source for `@debug`](https://github.com/sass/dart-sass/blob/6205eac5d149b21154ca044ebfc0cd55631346d2/lib/src/visitor/evaluate.dart#L1175)

Here is a script to reproduce the issue.

```js
const sass = require('sass');

sass.compileString('@warn hello;\n@debug world;', {
  logger: {
    warn: (...args) => console.log(...args), // span is undefined
    debug: (...args) => console.log(...args) // span is defined
  }
});
```

**Comment by nex3** [comment]
This is intentional. [Per the spec](https://github.com/sass/sass/blob/main/spec/js-api/logger/index.d.ts.md#warn), warnings for `@warn` only include a stack trace, not a span. This is for a combination of two reasons:

1. When a span _is_ passed to `@warn`, it's generally expected to be displayed to the user as an indication of a place the stylesheet is doing something it shouldn't (such as `$foo && $bar`).
2. The `@warn` rule is usually called from a function or a mixin, or possibly a nested series of functions or mixins. This means that the `@warn` rule itself is not usually the place where the user's stylesheet is doing something wrong, and so isn't useful to show in a span.
