### ISSUE TITLE
I would like to know which version of dart-sass supports node v10.18.0?

### ISSUE THREAD

**Issue by qinfeng0214** [sass/dart-sass#2224]
Hi,my project is node v10.18.0, I used node-sass, and now I want to use dart-sass, and I installed "sass": "^1.75.0", and it prompts "ReferenceError: globalThis is not defined". If dart-sass doesn't support node v10.18.0, then I can just continue using node-sass.
tks!

**Comment by nex3** [comment]
Node.js 10.x is _extremely_ outdated. It reached end-of-life on [April 30th, 2021](https://github.com/nodejs/Release?tab=readme-ov-file) and hasn't received new updates since then, including critical security updates. You absolutely should not be using it anymore.

Per [our compatibility policy](https://github.com/sass/dart-sass?tab=readme-ov-file#nodejs-compatibility), Dart Sass only supports current and LTS versions of Node.js. You can check [the versions page](https://www.npmjs.com/package/sass?activeTab=versions) to find the last version released while Node.js 10.x was in LTS and thus the last version guaranteed to support it: Dart Sass 1.32.12, released 28 April 2021.
