### ISSUE TITLE
trying ignore `mixed-decls` warning but still got these warning in Vite(`5.3.1`).

### ISSUE THREAD

**Issue by daiwanxing** [sass/dart-sass#2280]
just now upgrade my dependency of sass to the latest version (`1.77.8`) and restart, the app terminal output some warnings that i've never got.

```md
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
```

I have no time to solve these warnings, the easily way to me is make these warnings keep silence.

I followed the document instructions. but it's not work, I still got bunch of warnings. Is there something wrong with my configuration?

```js
// vite.config.js
css: {
    preprocessorOptions: {
      scss: {
        silenceDeprecations: ["mixed-decls"],
      },
    },
},
```

**Comment by jathak** [comment]
The deprecations options are only available in the modern JS API.

Vite is still using the legacy JS API, so you'll need to wait until https://github.com/vitejs/vite/issues/7116 is resolved to use these flags.

**Comment by Kamil-Jasinski** [comment]
Hi, @daiwanxing you can try this:

*vite.config.js
```
const SCSS_Logger = {
    warn(message, options) {
        // Mute "Mixed Declarations" warning
        if (options.deprecation && message.includes('mixed-decls')) {
            return
        }
        // List all other warnings
        console.warn(`▲ [WARNING]: ${message}`);
    },
};

export default defineConfig({
    plugins: [],
    css: {
        preprocessorOptions: {
            scss: {
                logger: SCSS_Logger,
            },
        },
    },
});
```

**Comment by replete** [comment]
Finally a workaround, I wish this was clear in the documentation that scss support is not up to date and so preprocessorOptions wont work as expected.

**Comment by supermueller** [comment]
You have to use at leaset the "modern" API: 

```js
export default defineConfig({
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern',
        silenceDeprecations: ['mixed-decls'],
      },
    }
  }
}
```

See also [Shared Options | Vite](https://vitejs.dev/config/shared-options#css-preprocessoroptions).

**Comment by lildinozzz** [comment]
> You have to use at leaset the "modern" API:
> 
> ```js
> export default defineConfig({
>   css: {
>     preprocessorOptions: {
>       scss: {
>         api: 'modern',
>         silenceDeprecations: ['mixed-decls'],
>       },
>     }
>   }
> }
> ```
> 
> See also [Shared Options | Vite](https://vitejs.dev/config/shared-options#css-preprocessoroptions).

that works! thank u

**Comment by johncip** [comment]
Hi, this is only indirectly related to `silenceDeprecations`, but I'm not sure if it's worth its own issue yet:

I get a lot of `mixed-decls` warnings, but they're all for code where the selectors used in the "normal" declarations and the ones in the nested rules **don't overlap**.

Here's an example:

```
10:24:53 css.1  |   ┌──> app/assets/stylesheets/components/avatar.scss
10:24:53 css.1  | 9 │     height: $size;
10:24:53 css.1  |   │     ^^^^^^^^^^^^^ declaration
10:24:53 css.1  |   ╵
10:24:53 css.1  |   ┌──> app/assets/stylesheets/_utilities.scss
10:24:53 css.1  | 2 │ ┌   &:active {
10:24:53 css.1  | 3 │ │     filter: brightness(1.25);
10:24:53 css.1  | 4 │ │   }
10:24:53 css.1  |   │ └─── nested rule
10:24:53 css.1  |   ╵
10:24:53 css.1  |     app/assets/stylesheets/components/avatar.scss 9:3  @import
10:24:53 css.1  |     app/assets/stylesheets/application.scss 24:9       root stylesheet
10:24:53 css.1  |
10:24:53 css.1  | WARNING: 22 repetitive deprecation warnings omitted.
```

In the example given [in the documentation](https://sass-lang.com/documentation/breaking-changes/mixed-decls), the `font-weight` rules overlap. But in my snippet, there are no such rules.

In other words, Sass is generating a warning about an upcoming to change to the lexical order of generated CSS, but warning on code blocks where the lexical order doesn't matter, since, once the browser adds up the rules for affected elements, their computed rulesets will be exactly the same as before.

Can someone point out if I'm missing something? From what I can tell, the current scope of the warnings **is a bug** -- especially given that, not only is the warning triggered by unaffected code, the usage itself isn't deprecated, that is, nested blocks and top-level declarations can continue to exist.

I don't object to the warning itself, so I don't think this is a retread of https://github.com/sass/dart-sass/issues/2276. But if, hypothetically, Sass were to start replacing all color names with hex literals, it'd be wrong to print deprecation warnings on font rules. False alarms dangerous because they *encourage people to silence the alarm*, and sure enough, half of the text on the doc page explaining the change is about how to silence warnings.

Am I missing something?

**Comment by replete** [comment]
@johncip Make a new issue for visibility, you've pinged contributors in here for a related but different issue and unlikely maintainer is going to read messages in closed threads. Good luck

**Comment by nex3** [comment]
@johncip It's more complex than it looks to only warn for rules that are known to have the same specificity—it means we have to compare the parent rule against _all_ previous rules in the current context rather than just checking whether at least one such rule exists. But I agree it would substantially reduce false positives, so I plan to look into it next week to see how feasible an implementation would be.

**Comment by johncip** [comment]
@nex3 devil is in the details, I should have known :D

thank you for taking the time to look into it!

**Comment by nex3** [comment]
@johncip I did in fact implement this check in https://github.com/sass/dart-sass/pull/2342. It's not property-aware—we really don't want to have to track the specific semantic details of all the defined CSS properties—but it does keep track of selector specificity which substantially reduces false positives.

**Comment by johncip** [comment]
Seems like a useful approach... upgrading got rid of all of my false positives, thank you!

**Comment by AndrewElans** [comment]
Configuring [Bootstrap 5.3](https://getbootstrap.com/docs/5.3/getting-started/vite/#configure-vite)

I have this gone `Warning: mixed-decls deprecation is obsolete. If you were previously silencing it, your code may now behave in unexpected ways.` by commenting-out this option:

```js
{
      preprocessorOptions: {
          scss: {
              silenceDeprecations: [
                  'import',
                  //'mixed-decls',
                  'color-functions',
                  'global-builtin'
              ]
          }
      }
  }
```

**Comment by jin395** [comment]
> You have to use at leaset the "modern" API:
```

export default defineConfig({
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern',
        silenceDeprecations: ['mixed-decls'],
      },
    }
  }
}
```
> See also [Shared Options | Vite](https://vitejs.dev/config/shared-options#css-preprocessoroptions).

Thank u.
But, the type 'api' did not exist in 'SassPreprocessorOptions',
so I deleted that line and ran the project again, and the problem was solved.
I recommend this to anyone in a similar situation!
