### ISSUE TITLE
dart-sass doesn't support ComplexSelector inside a ExtendRule 

### ISSUE THREAD

**Issue by AlexanderJohr** [sass/dart-sass#234]
I'm trying to move from node-sass to dart-sass.

dart-sass stops when it encounters this extend rule `@extend .btn-primary:hover`. node-sass is able to compile it.

I found out that in the method `visitExtendRule` only a `SimpleSelector` is parsed, but `:hover` makes that it's not simple.

```dart
  Value visitExtendRule(ExtendRule node) {
    if (!_inStyleRule || _declarationName != null) {
      throw _exception(
          "@extend may only be used within style rules.", node.span);
    }

    var targetText = _interpolationToValue(node.selector, warnForColor: true);

    var target = _adjustParseError(
        targetText.span,
        () => new SimpleSelector.parse(targetText.value.trim(),
            allowParent: false));
    _extender.addExtension(_styleRule.selector, target, node, _mediaQueries);
    return null;
  }
```

**Comment by nex3** [comment]
This is intentional; the old extend behavior for complex selectors was never really intended, and is currently deprecated (although the deprecation has yet to be implemented in LibSass; see https://github.com/sass/libsass/issues/2418). See https://github.com/sass/sass/issues/1599 for details.

I recommend just writing `@extend .btn-primary` instead.
