### ISSUE TITLE
color.channel can not auto convert between spaces and wrong docs about it

### ISSUE THREAD

**Issue by Mister-Hope** [sass/dart-sass#2353]
Reproduction: https://sass-lang.com/playground/#eJwzNHAoLU5VUCpOLC62Ss7PyS9SsubiUgGzrBSU00zTzNPSgCIOKalJpekKYHG95IzEvLzUHA2IMh0F9fKMzJLUvNTiYnVNawAzfhqY

```scss
@use "sass:color";

$color: #f5f7ff;

@debug color.channel($color, 'whiteness');
```

```

$channel: Color #f5f7ff has no channel named whiteness.
  ╷
5 │ @debug color.channel($color, 'whiteness');
  │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 5:8  root stylesheet
```

I don't think this is the expected behavior.

The docs says:

> ⚠️ Heads up!
>
> Because color.whiteness() is redundant with [color.channel()](https://sass-lang.com/documentation/modules/color/#channel), it’s no longer recommended. Instead of color.whiteness($color), you can write [color.channel($color, "whiteness")](https://sass-lang.com/documentation/modules/color/#channel).

However, the correct name should be lightness or blackness on the [color space docs](https://sass-lang.com/documentation/values/colors/). Something worth noting is that the deprecation also requires users to convert color space manually, as `color.channel` won't do that. An exmaple here:

```scss
@use "sass:color";

$color: #f5f7ff;

// $channel: Color #f5f7ff has no channel named lightness.
@debug color.channel($color, 'lightness');
// works and return 98.0392156863%
@debug color.channel(color.to-space($color, hsl), 'lightness');
```

So I believe at least the docs needs an update.

If the current behavior of `color.channel` is a bug, and sass team believes a channel name could be returned with any legacy color space by automatically converted to a correct space behind the sence, then only whiteness and blackness should be corrected in docs.

Otherwise, every deprecation about `color.channel` should be corrected, like `color.red($color)` must be replaced by `color.channel(color.to-space($color, rgb), 'red')`, unless the developer is sure that `$color` MUST be in rgb space

**Comment by nex3** [comment]
`color.channel($color, "whiteness")` is valid, but only if the color is in the HWB color space ([example](https://sass-lang.com/playground/#eJwzNHAoLU5VUCpOLC62Ss7PyS9SsubiUgGzrBQyypM0jIwsFCzN9AzMLUyMDY3NjUxVFQxUNYGKHFJSk0rTFcBK9ZIzEvPyUnM0IDp1FNTLMzJLUvNSi4vVgWoB5+0eCA==)). From [the `color.channel()` documentation](https://sass-lang.com/documentation/modules/color/#channel): 

> Returns the value of `$channel` in `$space`, which defaults to `$color`’s space.

When you call `color.channel(#f5f7ff, "whiteness")`, the `$space` argument defaults to `rgb` because that's the color space of hex colors. If you explicitly pass `$space: hwb`, it will work regardless of the space of the input color ([example](https://sass-lang.com/playground/#eJwzNHAoLU5VUCpOLC62Ss7PyS9SsubiUgGzrBSU00zTzNPSgCIOKalJpekKYHG95IzEvLzUHA2IMh0F9fKMzJLUvNTiYnUdBZXigsTkVCuFjPIkTWsAqloerw==)).

It is probably worth adding the explicit `$space` parameter to the deprecation.
