### ISSUE TITLE
meta.load-css, @at-root, and parent selectors...

### ISSUE THREAD

**Issue by vena** [sass/dart-sass#2406]
Not sure if this is a bug or I'm seriously Doing It Wrong. I am looking to bring a project up to date, taking a hint from the migrator and replacing `@import` rules with `meta.load-css()`. Several of the files are imported inside a selector from a parent file and have "top-level" parent selectors, expecting the previous `@import` behavior which allowed this and parsed out the selector from the parent file where it was imported. Using `meta.load-css`, this now errors, top-level parent selectors are not allowed, full stop.

I thought i could deal with this (in a less than ideal way) by wrapping the child file rules which use parent selectors in `@at-root .parent_selector {}` however there's some funky behavior there...

parent file:
```
.masthead {
  @include meta.load-css("menu");
}
```

menu.scss:
```
@at-root .masthead {
  &.solid .menu {
    color: black;
  }
}
```

Resulting rule:
```.masthead .masthead.solid .menu```

Assuming that load-css creates a new document root (which seems wrong?), I tried...
```
@at-root {
  &.solid .menu {...
```

But again error, top-level parent selectors are not allowed. So it's not creating a new document root? But it also is.

Thanks to anybody that can help me out... What's expected here?

**Comment by nex3** [comment]
Unlike `@import`, which re-evaluated files from scratch every time they were loaded, in the module system a given module is only ever evaluated once. This means you can `@use` the same file many times without duplicating its CSS or re-running its code over and over, but it also means that the evaluation has to be context-independent. Even if you `@include meta.load-css()` within a parent selector, the module can't "see" that parent selector.

 This is one reason we strongly recommend using mixins instead of top-level CSS. If `menu.scss` instead defined:

```scss
@mixin menu {
  &.solid .menu {
    color: black;
  }
}
```

then you could write

```scss
@use "menu";

.masthead {
  @include menu.menu;
}
```

in your parent file and it would work the same way it did before.

**Comment by vena** [comment]
thanks, @nex3!

does that mean there's some unexpected behavior when it comes to the `@at-root` rule that ends up including the parent file selector? the docs for @at-root don't suggest it should ever be anything but the document root.

**Comment by nex3** [comment]
I guess whether it's unexpected or not depends on what you expect :sweat_smile:. It is certainly true that `@at-root` will not move through the outer context, because again the loaded file is converted to CSS _first_ before it's nested within the parent selector. If that's your mental model, then you're likely to expect what actually happens. If your mental model is that it works exactly like `@import`, then you're likely to be surprised.
