### ISSUE TITLE
[Feature] Allow nesting with SCSS

### ISSUE THREAD

**Issue by ggedde** [sass/dart-sass#2448]
I know there is discussion about Nesting with Plain CSS #3524

However, I am looking for a way to keep nesting when compiling SCSS.
Essentially something like adding an option like `--nested` to my sass cli script.
In doing so sass should keep my nesting as is, but still do everything else.

With that said there may be a need for  `--nested` and `--nested-with-selector` which keeps the `&` symbol for older browsers.

I know that CSS Nesting is not fully supported by all browsers, but this option would make it an Opt-In feature and on my projects I am only concerned about modern browsers and have no need for older browser support.

1. Is this something that will be supported?
2. If so, in what version are you looking to add this?

Alternatively, does anyone know of a post-css processor that will nest my css for me?

I have tested my project by manually re-nest my script after sass has compiled it and it took the file size down by 45% and everything worked as expected, but as you would guess this manual process is too tedious and is not something I would want to do continuously.

Thanks,

**Comment by jathak** [comment]
As described in [this blog post](https://sass-lang.com/blog/sass-and-native-nesting/), if we ever do decide to phase out Sass nesting and just emit plain CSS nesting instead, we wouldn’t do so until [98% of the global browser market share](https://github.com/sass/dart-sass#browser-compatibility) supported native nesting.

We don't add flags that change the semantics of the CSS generated by Sass because we want to ensure the portability of Sass code (that is, you should be able to tell what CSS will be generated by a given piece of Sass code without knowing any external configuration)
