### ISSUE TITLE
Feedback regarding makinga mess of upgrade.

### ISSUE THREAD

**Issue by lmf-git** [sass/dart-sass#2450]
The chaos caused with this very over-complicated upgrade and all of the breaking changes have made me consider using somethingelse.

https://github.com/sass/dart-sass/issues/2352

**Comment by nex3** [comment]
What specifically would you have preferred we do differently here? We [announced the upcoming change](https://sass-lang.com/blog/request-for-comments-new-js-api/) more than three years ago, and we provided well over two and a half years between [releasing the new API](https://github.com/sass/dart-sass/pull/1569) and [starting to emit deprecation warnings](https://github.com/sass/dart-sass/pull/2343). During this time, it was clearly documented [on the Sass website](https://sass-lang.com/documentation/js-api/#md:legacy-api) and [in JSDoc annotations](https://github.com/sass/sass/blob/831f780a414f35d631e6c836e175793282a8d460/js-api-doc/legacy/render.d.ts#L9-L11) that the legacy API was deprecated.

Before we started emitting deprecation warnings for the legacy API, we made sure there were fine-grained options to control deprecation messages in both [the modern API](https://sass-lang.com/documentation/js-api/interfaces/options/#silenceDeprecations) *and* [the legacy API](https://sass-lang.com/documentation/js-api/interfaces/legacysharedoptions/#silenceDeprecations). We even [reached out](https://github.com/vercel/next.js/discussions/67931) to various frameworks we knew were still using the legacy API to warn them directly of the upcoming change.

Ultimately, the experience a user undergoes is primarily in the hands of the framework they interact with rather than the tools that framework uses. If we provide as much notice and documentation as we can of an upcoming change and the framework ignores it, there's very little we can do. If we provide detailed options to control warnings and the framework doesn't expose them to users, or doesn't explain to users how to access them, there's very little we can do. So I ask you: how did _we_ "make a mess" of this upgrade? Or are you just frustrated because something changed and instead of choosing to help make the process better, you chose to lash out?

**Comment by lmf-git** [comment]
The documentation for it was bad, deprecation warnings were late. Obviously
you didn’t give enough time because every framework experienced a flood of
this issue.

I also have serious skepticism about whether any of it was needed or even
improves anything.

Also, your defensive, whiny response isn’t very indicative of a serious
team/project.



LM Fielding

Founder

Dreamsbyte
+44 738-980-5421 <+44+738-980-5421>
***@***.***
https://dreamsbyte.com
[image: facebook] <https://www.facebook.com/dreamsbyte>
[image: linkedin] <https://linkedin.com/company/dreamsbyte>
[image: instagram] <https://www.instagram.com/dreamsbyte/>

**Comment by lmf-git** [comment]
You wasted a lot of developer time, the migration was not smooth so there’s
obviously something to improve here but you’d rather put my factual
observations into quotes and act like a narcissist.

If you hadn’t fucked up, then this conversation wouldn’t exist. Would it?

When your software works well then people don’t notice it. If i’m noticing
this… well you know what that means.

I’m going to swap to pure CSS after this experience with this project and
you. I think you’ve outlived your usefulness.

Good luck finding your next job.
LM Fielding

Founder

Dreamsbyte
+44 738-980-5421 <+44+738-980-5421>
***@***.***
https://dreamsbyte.com
[image: facebook] <https://www.facebook.com/dreamsbyte>
[image: linkedin] <https://linkedin.com/company/dreamsbyte>
[image: instagram] <https://www.instagram.com/dreamsbyte/>

**Comment by nex3** [comment]
This is way out of bounds for the Sass code of conduct, and basic decency when interacting with someone who's providing you a product for free.
