### ISSUE TITLE
Color, variables defined in hexadecimal are converted to rgb.

### ISSUE THREAD

**Issue by ysakmrkm** [sass/dart-sass#2456]
Is it the default behavior that colors defined in hexadecimal are converted to rgb when processed by, for example, mix?
Since they are defined in hexadecimal, I would like to get them in hexadecimal.
If it is the default behavior, is there a way to convert to hexadecimal?

https://sass-lang.com/documentation/values/colors/#color-functions

```
@use 'sass:color';

$venus: #998099;

@debug color.scale($venus, $lightness: +15%, $space: oklch);
// rgb(170.1523703626, 144.612080603, 170.1172627174)
@debug color.mix($venus, midnightblue, $method: oklch);
// rgb(95.9363315581, 74.5687109346, 133.2082569526)
```

**Comment by nex3** [comment]
Converting these to hexadecimal representations would lose precision, which with the introduction of [CSS Color 4](https://www.w3.org/TR/css-color-4/) and high-color-depth displays can be observable. This would be an unsafe optimization to make, and Sass will always prioritize correctness over terse output. In addition, the `rgb()` syntax is supported by all browsers and _should be_ supported by all tools since it's been around since CSS 1.

If just you're looking for terser stylesheets, I recommend using a minifier like [cssnano](https://cssnano.github.io/cssnano/) as a post-processing step. It's capable of converting high-precision colors into lower-precision hex codes.

**Comment by soundasleep** [comment]
@nex3 Unfortunately, I think `rgb(float, float, float)` is _not_ valid CSS 1, as per the spec https://www.w3.org/TR/CSS1/#color-units:

> The format of an RGB value in the functional notation is 'rgb(' followed by a comma-separated list of three numerical values (either three integer values in the range of 0-255, or three percentage values in the range of 0.0% to 100.0%) followed by ')'. Whitespace characters are allowed around the numerical values. 

It is also not valid CSS 3, as per the spec: https://www.w3.org/TR/css-color-3/#rgb-color

> The format of an RGB value in the functional notation is ‘rgb(’ followed by a comma-separated list of three numerical values (either three integer values or three percentage values) followed by ‘)’. The integer value 255 corresponds to 100%, and to F or FF in the hexadecimal notation: rgb(255,255,255) = rgb(100%,100%,100%) = #FFF. White space characters are allowed around the numerical values. 

I'm not sure what CSS compatibility you're aiming to support with SASS - is it CSS 4 minimum?

I'm having an issue where upgrading to Dart-sass is breaking colours because `rgb(95.9363315581, 74.5687109346, 133.2082569526)` is NOT valid CSS. It may work in many browsers, but it's not working in my particular CSS parser (which does not support floating point terms). And I could add a post-processing step, but then I'd lose SASS's `watch` functionality...

You may want to either change Dart-Sass to export `rgb(12.34%, 12.34%, 12.34%)` if you want to maintain the HDR precision, as it looks like that _is_ valid CSS (at the very least, CSS 1 + CSS Color 3 specifies percents as a float range), or to add some option or workaround to output hexcodes or integer RGBs.

**Comment by nex3** [comment]
From the [browser compatibility policy](https://github.com/sass/dart-sass/#browser-compatibility):

> If a change would break compatibility with less than 2% of the global market share of browser according to [StatCounter GlobalStats](https://gs.statcounter.com/), we may release a minor version of Dart Sass with that change.

That said, it's true that floating-point numbers [don't meet that bar currently](https://caniuse.com/mdn-css_types_color_rgb_float_values) (largely because of the continued prevalence of Chrome <=65). I've filed https://github.com/sass/dart-sass/issues/2799 to track this.

---

> I'm having an issue where upgrading to Dart-sass is breaking colours because `rgb(95.9363315581, 74.5687109346, 133.2082569526)` is NOT valid CSS.

This isn't accurate. This has been valid since [CSS Colors 4](https://www.w3.org/TR/css-color-4/#rgb-functions), which supports the syntax `rgb( <number>#{3} , <alpha-value>? )`.

> It may work in many browsers, but it's not working in my particular CSS parser (which does not support floating point terms).

This is an issue you should file with that parser, as it's now years out-of-date with respect to valid CSS syntax.

**Comment by soundasleep** [comment]
Thank you very much @nex3 ! I agree the parser I'm using needs to be updated (it's https://github.com/radkovo/jStyleParser ) but unfortunately it'd involve rebuilding ANTLR4 sources and basically updating the entire project to support CSS 4, and it's a very niche use case...
