### ISSUE TITLE
Size of the `dart` binary has nearly tripled in last few months

### ISSUE THREAD

**Issue by chdiza** [sass/dart-sass#261]
I'm not sure if this is on purpose or not, but I've noticed that in the official releases for macOS 64, the `src/dart` binary contained in them is now 28.7MB, but the corresponding binary in beta4 was only  10.9MB.

I'm not knowledgeable about how all this works, but if `dart-sass` acquires features and abilities (as it has over the last few months) isn't it only the snapshot that should grow and not the `dart` binary?

**Comment by nex3** [comment]
Dart Sass just bundles the latest official Dart binary. @mraleph is this size increase known/expected?

@chdiza Is the increased size causing problems for you?

**Comment by chdiza** [comment]
It's not causing problems, but one thing I was delighted to see when I first discovered dart-sass months ago was that it was very lightweight even if one didn't already have the Dart SDK installed.  As that Dart binary grows (particularly if it keeps growing at the rate it has recently), the reason to use dart-sass rather than either sassc or node-sass decreases.

**Comment by mraleph** [comment]
The size increase is transitionary. I looked a breakdown on Linux and ~18MB of 27MB binary is spent on

* Kernel platform in Dart 1 mode (~6MB) - this contains both original source and kernel AST representation for all core libraries;
* Kernel platform in Dart 2 mode (~6MB) - this contains both original source (same source as above) and kernel AST representation for all core libraries (note: it's the same source - but kernel ASTs are different in places where strong mode type inference applies);
* CFE app-jit snapshot (~6MB) - this contains CFE token stream and optimized JIT compiled code 

I think there is plenty of room for improvement here - the binary size will go down when we remove Dart 1 support from the VM (so we can also delete the Dart 1 core libraries binary). Then we have some plans to explore a more efficient ways to compile CFE ahead of time, instead of using app-jit snapshot. We will also remove all parts associated with the C++ parser once Dart 1 is gone - but that is much smaller than the CFE snapshot.

**Comment by nex3** [comment]
Since it sounds like the size will go down again eventually, and definitely won't continue increasing, I'm going to close this out.

**Comment by chdiza** [comment]
Good to know, thanks.

**Comment by chdiza** [comment]
FYI, I don't know if this is intentional or not, but the size of `dart.snapshot` quadrupled between 1.6.2 and 1.7.0.  It's about 2.8MB in 1.7.0, and about 700K in 1.6.2.

**Comment by nex3** [comment]
@mraleph It looks like the snapshot generated in Dart 2 mode is much larger than the one generated in Dart 1 mode. Do you know what's behind this increase? Is it on your radar?

**Comment by mraleph** [comment]
In Dart 2 script snapshots are just Kernel binaries - which by default contain both source and parsed AST. I guess that explains the size. If you strip the source, the size should go down. I don't think anybody is specifically looking at Kernel binaries size at the moment, but probably will be next Q when we will start finalizing the design of Kernel as a distribution format.

**Comment by nex3** [comment]
How do we compile with the source stripped?

**Comment by chdiza** [comment]
In 1.7.1, it's back down again.

**Comment by nex3** [comment]
1.7.1 is pinned to a version of Dart prior to Dart 2 being enabled by default.
