### ISSUE TITLE
Way to tell SASS version

### ISSUE THREAD

**Issue by vr8hub** [sass/dart-sass#308]
`sass --version` gives the *Dart* sass version, but it would be nice to also know the actual sass version that the sass executable is supporting (in this case, 3.5, I think).

Could another option, e.g. `--sass-version`, be added, or perhaps just append the sass version to the `--version` output, e.g. `1.2.1, sass 3.5`?

**Comment by nex3** [comment]
We aren't really tracking the version number of Sass as a language anymore. Dart Sass *roughly* supports the semantics of Ruby Sass's in-development 4.0 branch, but there are some features that match the Ruby Sass 3.5 behavior in order to ease migration, as well as features that don't exist in any version of Ruby Sass.

Going forward, we're going to talk more about which individual features an implementation supports rather than bundling features together into language versions. This will give LibSass more freedom to focus first on the features that matter most to their users, and it will give Dart Sass more freedom to add new features as quickly as possible without needing to wait for LibSass to reach compatibility with an arbitrary version number.
