### ISSUE TITLE
CompileStringAsyc() and race conditions when used in package build

### ISSUE THREAD

**Issue by nshahan** [sass/dart-sass#328]
I'm working on implementing an AsyncImporter to use in package [sass_builder](https://pub.dartlang.org/packages/sass_builder). I've got a working synchronous importer by wrapping async calls with `waitFor` from dart:cli but I would like to compare the performance with an async version.

For a given build target I am finding that calls to `canonicalize()` continue after the call `CompileStringAsyc()` has returned a value. This causes an error in package build: 
```
Concurrent modification during iteration: Instance of 'SplayTreeSet<AssetId>'
```
I don't have a proper stack trace to point to the call site in package sass because the error arises from the iteration site in package build. I do believe it is a call to `canonicalize()` that is causing the problem. 

How can we investigate this more?

**Comment by nex3** [comment]
If a call to `canonicalize()` is the root cause, then there are two ways it could stay alive after the compilation has finished: either the compilation logic could fail to wait on the returned future, or the implementation of `canonicalize()` could have asynchronous logic that doesn't get piped into the returned future. It looks like the asynchronous `_EvaluateVisitor` `await`s both of its calls to `.canonicalize()`, so it seems like the first place to look is probably your `canonicalize()` implementation.

**Comment by nshahan** [comment]
False alarm. The unawaited future in my code has been found. Now the question is why didn't the lint give any feedback for it.

https://github.com/dart-lang/linter/issues/1007
