### ISSUE TITLE
`dart-sass .` doesn't work, even though `sass .` works in ruby.

### ISSUE THREAD

**Issue by chdiza** [sass/dart-sass#346]
I'm trying to migrate from ruby-sass, and I've run into the following irritation.  I don't know whether it's a bug or intended.  I expect---based on my experience with ruby sass---to do `dart-sass .` and have every sass file `foo.sass` in the current working dir compiled to a corresponding `foo.css` in the current working dir.

Instead, `dart-sass .` results in `Error reading .: Cannot open file.`

I have found that `dart-sass .:.` works, but man that's awkward to type.

**Comment by nex3** [comment]
I decided to slightly change how path specifications work with Dart Sass to make `--update` more uniform with normal invocations of the executable. In Ruby Sass, the way paths were parsed was totally different in `--update` mode than it was in the default mode: not only did it allow `input:output` combinations that wouldn't work in normal mode, it considered an argument without a colon to implicitly mean "compile this to a CSS file or CSS files in the same location".

In Dart, the `--update` flag doesn't change anything about the parsing of arguments. This means that you can use `input:output` syntax without using `--update`, and it eliminates the need to have a `--force` flag (since that's now the default behavior). However, it does mean that if you want to compile an entire directory to CSS, you *must* pass it explicitly using colon syntax, as you've discovered with `.:.`.

**Comment by chdiza** [comment]
Thanks for the explanation. :)  I'll just make a wrapper of some sort to avoid the awkardness of "`.:.`"
