### ISSUE TITLE
Sass incorrectly parses #RRGGBBAA codes

### ISSUE THREAD

**Issue by michaelkolber** [sass/dart-sass#360]
When writing something such as

```sass
box-shadow: #0000006e 0 3px 5px 0px;
```

Sass outputs

```css
box-shadow: #000000 6e 0 3px 5px 0px;
```

which breaks the property.

**Comment by nex3** [comment]
Well this is *definitely* incorrect--in no world should the token `#0000006e` be parsed as a color followed by an identifier. This also reminds me that Dart Sass should be emitting deprecation warnings for hex colors that are ambiguous with IDs, *a la* https://github.com/sass/sass/issues/2179, so that we can eventually support parsing them as colors.
