### ISSUE TITLE
SourceMap: multiple lines incorrectly map to same source position

### ISSUE THREAD

**Issue by aleclarson** [sass/dart-sass#368]
The attached `issue.zip` package has the necessary steps to reproduce.

### [issue.zip](https://github.com/sass/dart-sass/files/2117575/issue.zip)

```sh
npm install
npm start
```

[Mappings in a gist](https://gist.github.com/aleclarson/b4f9497f17186b3db4f29f0aa2968191)

**Comment by nex3** [comment]
How is this affecting your use of Sass? Dart Sass intentionally generates pretty small source maps because, as far as I've tested, browsers only really care about the start position of selectors and declarations. [It looks like](https://sokra.github.io/source-map-visualization/#base64,LyogaHR0cDovL21leWVyd2ViLmNvbS9lcmljL3Rvb2xzL2Nzcy9yZXNldC8KICAgdjQuMCB8IDIwMTgwNjAyCiAgIExpY2Vuc2U6IG5vbmUgKHB1YmxpYyBkb21haW4pCiovCmh0bWwsIGJvZHksIGRpdiwgc3BhbiwgYXBwbGV0LCBvYmplY3QsIGlmcmFtZSwKaDEsIGgyLCBoMywgaDQsIGg1LCBoNiwgcCwgYmxvY2txdW90ZSwgcHJlLAphLCBhYmJyLCBhY3JvbnltLCBhZGRyZXNzLCBiaWcsIGNpdGUsIGNvZGUsCmRlbCwgZGZuLCBlbSwgaW1nLCBpbnMsIGtiZCwgcSwgcywgc2FtcCwKc21hbGwsIHN0cmlrZSwgc3Ryb25nLCBzdWIsIHN1cCwgdHQsIHZhciwKYiwgdSwgaSwgY2VudGVyLApkbCwgZHQsIGRkLCBvbCwgdWwsIGxpLApmaWVsZHNldCwgZm9ybSwgbGFiZWwsIGxlZ2VuZCwKdGFibGUsIGNhcHRpb24sIHRib2R5LCB0Zm9vdCwgdGhlYWQsIHRyLCB0aCwgdGQsCmFydGljbGUsIGFzaWRlLCBjYW52YXMsIGRldGFpbHMsIGVtYmVkLApmaWd1cmUsIGZpZ2NhcHRpb24sIGZvb3RlciwgaGVhZGVyLCBoZ3JvdXAsCm1haW4sIG1lbnUsIG5hdiwgb3V0cHV0LCBydWJ5LCBzZWN0aW9uLCBzdW1tYXJ5LAp0aW1lLCBtYXJrLCBhdWRpbywgdmlkZW8gewogIG1hcmdpbjogMDsKICBwYWRkaW5nOiAwOwogIGJvcmRlcjogMDsKICBmb250LXNpemU6IDEwMCU7CiAgZm9udDogaW5oZXJpdDsKICB2ZXJ0aWNhbC1hbGlnbjogYmFzZWxpbmU7Cn0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPW91dC5jc3MubWFwICovCg==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7QUFBQTtBQUFBO0FBQUE7QUFLQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtFQWFDO0VBQ0E7RUFDQTtFQUNBO0VBQ0E7RUFDQSIsImZpbGUiOiJvdXQuY3NzIn0=,LyogaHR0cDovL21leWVyd2ViLmNvbS9lcmljL3Rvb2xzL2Nzcy9yZXNldC8KICAgdjQuMCB8IDIwMTgwNjAyCiAgIExpY2Vuc2U6IG5vbmUgKHB1YmxpYyBkb21haW4pCiovCgpodG1sLCBib2R5LCBkaXYsIHNwYW4sIGFwcGxldCwgb2JqZWN0LCBpZnJhbWUsCmgxLCBoMiwgaDMsIGg0LCBoNSwgaDYsIHAsIGJsb2NrcXVvdGUsIHByZSwKYSwgYWJiciwgYWNyb255bSwgYWRkcmVzcywgYmlnLCBjaXRlLCBjb2RlLApkZWwsIGRmbiwgZW0sIGltZywgaW5zLCBrYmQsIHEsIHMsIHNhbXAsCnNtYWxsLCBzdHJpa2UsIHN0cm9uZywgc3ViLCBzdXAsIHR0LCB2YXIsCmIsIHUsIGksIGNlbnRlciwKZGwsIGR0LCBkZCwgb2wsIHVsLCBsaSwKZmllbGRzZXQsIGZvcm0sIGxhYmVsLCBsZWdlbmQsCnRhYmxlLCBjYXB0aW9uLCB0Ym9keSwgdGZvb3QsIHRoZWFkLCB0ciwgdGgsIHRkLAphcnRpY2xlLCBhc2lkZSwgY2FudmFzLCBkZXRhaWxzLCBlbWJlZCwKZmlndXJlLCBmaWdjYXB0aW9uLCBmb290ZXIsIGhlYWRlciwgaGdyb3VwLAptYWluLCBtZW51LCBuYXYsIG91dHB1dCwgcnVieSwgc2VjdGlvbiwgc3VtbWFyeSwKdGltZSwgbWFyaywgYXVkaW8sIHZpZGVvIHsKCW1hcmdpbjogMDsKCXBhZGRpbmc6IDA7Cglib3JkZXI6IDA7Cglmb250LXNpemU6IDEwMCU7Cglmb250OiBpbmhlcml0OwoJdmVydGljYWwtYWxpZ246IGJhc2VsaW5lOwp9Cg==) we're correctly mapping the generated selector to the source selector, so browsers should handle this appropriately.

**Comment by nex3** [comment]
> Did you test doing..
> ```js
> [ [ 0, 0, 5, 0 ] ],
> [ ],
> [ ],
> ```
> ..instead of..
> ```js
> [ [ 0, 0, 5, 0 ] ],
> [ [ 0, 0, 5, 0 ] ],
> [ [ 0, 0, 5, 0 ] ],
> ```
> ..or are there debuggers that freak out when a line has no segments?
> 
> I'm asking because I've seen other tools generate source maps like the first example, and they seem to work fine (but I haven't tested on every popular debugger, maybe you have?).

The spec is extremely unclear in general, and I don't know of anyone who's done a thorough survey of *de facto* implementation behavior, but my impression is that each group in the "mappings" data represents exactly one line of the generated output. The spec says (emphasis mine):

> each group represent[s] **a** line in the generated file

This suggests that we need to generate a separate group for each line, even when it refers to the same location as the previous line. This matches the behavior of the source map viewer. This viewer is of course non-normative but represents one reasonable interpretation of the spec, and an implementation we care about insofar as users might use it to inspect the source maps Sass generates.

> I made a tool that merges source maps, and I need to know if I should handle cases like this, or consider them invalid.

Leaving aside the question of whether it's *necessary* to generate multiple mappings back to the same source location in this instance, it's certainly *valid*, and comes up in cases that don't necessarily involve multiple lines. For example, [this compilation](https://sokra.github.io/source-map-visualization/#base64,YSB7CiAgYjogdmFsdWU7CiAgYzogdmFsdWU7Cn0KCi8qIyBzb3VyY2VNYXBwaW5nVVJMPW91dC5jc3MubWFwICovCg==,eyJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJ0ZXN0LnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBRUE7RUFDRSxHQUhJO0VBSUosR0FKSSIsImZpbGUiOiJvdXQuY3NzIn0=,JHZhcjogdmFsdWU7CgphIHsKICBiOiAkdmFyOwogIGM6ICR2YXI7Cn0K) links both declarations' values back to the original definition of the variable.
