### ISSUE TITLE
--watch cmd stops to compile in case of a single error

### ISSUE THREAD

**Issue by gernotpokorny** [sass/dart-sass#401]
`sass --watch input.scss output.css`

You introduce an error --> save the file --> sass throws an error --> cmd does show the error
You fix the typo --> save the file --> sass does not compile anymore

then you have to press ctrl+c in the cmd and restart via `sass --watch input.scss output.css`.

I mean that workflow is really irritating. You fixed the error and it does still completely stop and still show you the error. That makes no sense to me. Why not just compile when the error is fixed, why just stop completly? Is this on purpose? 

info: I installed sass via `npm install -g sass`

**Comment by nex3** [comment]
What does `sass --version` print? What's the contents of your input file?

**Comment by beastdestroyer** [comment]
@nex3 It happens to me also, I use Dart Sass 1.10.0 and it happens with any error, most commonly with brackets, but pretty much any syntax error in SCSS will get it to block, I'll provide an example:

Let's say you have the following code:
```
p {
  font-size: 16px;
  line-height: 50px;
  i {
    font-size: 18px;
    &:hover {
       background-color: #f1f1f1;
    }
  }
}
```
Pointless code I know, but for demonstration, say you remove one of the brackets, the Sass compiler just hangs as mentioned in the original post. If working with media queries, this error will pop up more often since there is lots of stuff to be processed, just removing a bracket, misspelling a property name can cause it. Hope this provides more help?

**Comment by nex3** [comment]
Thanks @beastdestroyer, I can reproduce now.
