### ISSUE TITLE
File names are converted to lowercase in source map

### ISSUE THREAD

**Issue by imhangoo** [sass/dart-sass#540]
Say my Main.scss file has this:
`@import "TestFile";`

Then I run: 
`sass --source-map Main.scss Main.css`

Then the generated source map will have:
`sources: ["main.scss","testfile.scss"]`

This will cause file not found in case sensitive web server, http://xxx.xxx.xxx/mian.scss will not get the content from http://xxx.xxx.xxx/Mian.scss
May I know if this is by design? And if there is any walkaround to make the generated source list match the original file name case?

Thanks!

**Comment by nex3** [comment]
I'm guessing you're using Windows?

Dart Sass canonicalizes the URLs it imports, so that it doesn't re-parse a file multiples times if you write both `@import "main.scss"` and `@import "Main.scss"`. This canonicalization will become even more important with [the new module system](http://sass.logdown.com/posts/502818-request-for-comments-module-system-proposal), where it will be used to ensure that a given module is only evaluated once.

I'll look into how feasible it is to de-canonicalize file case before creating source maps. In the meantime, it seems that your server isn't respecting the fact that the filesystem it's serving from is case-sensitive. Fixing that that may be a way to remedy this in the short term, or if it turns out to be infeasible to fix on the Sass side.

**Comment by imhangoo** [comment]
Thank you so much for your suggestions, they are very helpful!
