### ISSUE TITLE
Support passing individual directories to the CLI

### ISSUE THREAD

**Issue by fschutt** [sass/dart-sass#543]
A year ago I developed a website with ruby-sass. Now with dart-sass I'm trying to get the website running again. So I installed dart-sass, added it to the PATH (on Windows). I am using the MinGW shell on Windows, added the folder under "C:/Program Files (x86)/Sass". However, now I'm getting a confusing error:

```
sass.bat --watch ./website/public/css
--watch is not allowed when printing to stdout.
```

What does that mean - the entire point of the "watch" command is to hot-reload and print errors to stdout. Why can't I just watch a directory on Windows? I can get my files to compile, if I add `> /dev/null` at the end, however, then dart-sass immediately exits (but compiles the files, at least). However, that's not hot-reloading, so... what's the point of the watch command, then? I'm not sure if this is a bug related to Windows - the error also appears if I run sass via cmd.

All I want is for sass to start (like ruby-sass did) and watch my files, so that it prints errors as it hot-reloads the files - however, how am I supposed to see the error output without using stdout? And how do I get hot-reload to work at all under Windows?

**Comment by nex3** [comment]
Dart Sass's `--watch` syntax is somewhat different than Ruby Sass's. In order to a compile all the Sass files in a directory to CSS files in the same directory, you need to write `sass --watch website/public/css:website/public/css`.

That said, we should probably make this use-case easier by detecting that you passed a directory and handling it specially, though.
