### ISSUE TITLE
Why no watchmode on stdout printing?

### ISSUE THREAD

**Issue by strychnide** [sass/dart-sass#564]
I'm wrapping dart-sass in node (because it's a lot faster than the js version atm), and i'd like to read the input from stdout while watching the files (to do manipulation/save them on a in-memory fs and so on). Is there a clear reason for not enabling watching while printing to stdout? Can we at least talk about an override optional flag?

(workaround -> using /dev/stdout, but I'd like a more "official" way)

**Comment by nex3** [comment]
`--watch` mode inherently involves compiling multiple files to multiple destinations, and stdout is only one destination. There would be no way to tell which chunk of CSS corresponded to which input. Also, generally speaking `--watch` mode is intended for human convenience rather than tooling.

If you're looking for an efficient way to wrap the Dart VM version in a JS API, https://github.com/sass/dart-sass/issues/248 might be a better approach. If you're willing to sign up to maintain a full-featured JS wrapper, we could start working on a proper protocol to make that work.

**Comment by strychnide** [comment]
Looked at what node-sass does right now,  doesn't look too big of a problem mantaining a similar wrapper without the cpp bridge, I'm in.
(On a side note, I'm pro protobufs for this one)

**Comment by nex3** [comment]
@strychnide That's great! Let's move discussion over to #248.
