### ISSUE TITLE
Include error messages in compiled output

### ISSUE THREAD

**Issue by JQOz** [sass/dart-sass#657]
Hi,

if I install Ruby-Sass, I can see all the errors on browser but with the other sass versions ( sass --version: 1.19.0) I can see all errors on Terminal but nothing on browser and this is not so useful. Thats way I have installed the Ruby-Sass, which is not recommended.

Has anyone idea How to show sass compilation errors in the browser with the Sass-version 1.19.0.

I am using Mac-Majove and working on Wordpress project. 
Sass version is "Ruby Sass 3.7.4"

thanks 
JQ

**Comment by nex3** [comment]
For background: when Ruby Sass encounters an error, by default it produces a CSS file that includes the error message and stack trace in a comment as well as in the `content` property of a `body::before` style rule in order to make it immediately visible during users' edit/refresh cycle. Dart Sass doesn't do this currently, but it probably should.
