### ISSUE TITLE
Importers should take precedence over load paths in the JS API

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#681]
To match the behavior of Node Sass, importers should take precedence over load paths.

**Comment by B-Stewart** [comment]
@nex3 just confirming that this fix was released? We're trying to move from node-sass to dart-sass and this is currently our blocker. The `importer` function seems to never be called unless it can't find the file, whereas with `node-sass` it is working for each `@import`. Changelog I think makes reference to this being fixed in 1.20.2, but that isn't on npm any longer, I've tested on 1.21.0 and 1.20.3 to no avail.

If this should be fixed, I can try to make a small reproduction case for you, but didn't want to take the time if it wasn't actually released and I was mistaken. We are using it within `gulp-sass`, but don't think it's on that library.

```
gulp.pipe(
            $.sass({
                importer: storeImporter
            })
        )

const storeImporter = (importPath, sourcePath, done) => {    
//... logic removed for clarity

    if (files.some(f => f.includes(lookingOverride))) {
        return {
            file: overrideImport
        };
    } else {
        return null;
    }
};
```

**Comment by nex3** [comment]
@B-Stewart Yes, this was released in 1.20.2 and should be in all releases after that.

**Comment by grtan** [comment]
> @nex3 I still experience this issue on 1.26.10.
> It works on `sass` files but not for `scss` files.
> Can you tell why?

I also encountered the same problem with scss files

**Comment by MBelniak** [comment]
@nex3  Are there any plans of addressing the problem with scss files?

**Comment by Awjin** [comment]
Could you provide a minimal reproduction of how this is breaking in scss?

**Comment by MBelniak** [comment]
Ekhm, I've created a minimal reproduction repo and it turns out that it works OK even with scss files o.O. I assumed it was not working based on the previous comments.
Here's the repo: https://github.com/MBelniak/dart-sass-repro/tree/with-dart-sasss
Indeed, with dart-sass 1.20.1 the custom importer is not called, but with versions above it's called as expected.
@YonatanKra  @grtan Can you share your experience, how it's not working for you?

**Comment by MBelniak** [comment]
Ekmh, I've created maybe not so minimal reproduction repo and it turns out the importer is called as it should even for scss files o.O. Maybe I did a wrong assumptions based on the previous comments. Indeed, it doesn't work with version prior to 1.20.2.
Repo: https://github.com/MBelniak/dart-sass-repro/tree/with-dart-sasss
@YonatanKra  @grtan Can you share your experience, how it's not working for you?

**Comment by MBelniak** [comment]
I came back to this topic and it's indeed not working as expected. The first @import is correctly handled by a custom resolver, but if the imported file has another @import, the resolver is not used.

**Comment by nex3** [comment]
Again, can you provide a minimal reproduction?

**Comment by MBelniak** [comment]
Is the one I linked inappropriate or too complex? It describes the case I rely on. If you want to have an example without webpack and with the simplest possible setup, I can create such on Saturday.

**Comment by nex3** [comment]
> If you want to have an example without webpack and with the simplest possible setup, I can create such on Saturday.

Yes, that's what I'm looking for.

**Comment by MBelniak** [comment]
@nex3  https://github.com/MBelniak/dart-sass-repro/tree/minimal-repro
See the readme. Let me know if there's anything more I can explain.

**Comment by nex3** [comment]
@MBelniak Your example doesn't use load paths, so I don't think it's actually related to this issue. Regardless, it's working as intended:

1. `@import 'exists'` is resolved relative to `index.scss`. Because `index.scss` was loaded from the filesystem, it implicitly uses the built-in filesystem importer to handle its relative resolution.

2. `@import 'missing'` attempts to be resolved relative to `index.scss` using the built-in filesystem importer. However, `file:///path/to/cwd/missing.scss` doesn't exist, so the filesystem importer returns `null`.

3. `@import 'missing'` is then passed to your custom importer's `canonicalize()` method. This also returns `null`.

4. Finally, since there are no more importers or load paths, `@import 'missing'` throws an error.

**Comment by MBelniak** [comment]
Hi @nex3,
`Your example doesn't use load paths, so I don't think it's actually related to this issue` - that is true. Should I start another conversation under #574?
Regardless, I tried using findFileUrl function to override the behavior of filesystem importer, but the effect is the same - it is not called if the imported file exists. I think this was the main concern raised in #574. Is it planned to be changed?

BTW, the require statement in the first example at https://sass-lang.com/documentation/js-api/interfaces/FileImporter should be changed to pathToFileURL.

**Comment by nex3** [comment]
> `Your example doesn't use load paths, so I don't think it's actually related to this issue` - that is true. Should I start another conversation under #574?

We can continue discussing wherever.

> Regardless, I tried using findFileUrl function to override the behavior of filesystem importer, but the effect is the same - it is not called if the imported file exists. I think this was the main concern raised in #574. Is it planned to be changed?

No, this is the intended behavior. Filesystem importers aren't meant to override local relative loads—that's generally not desirable behavior, because it breaks users' ability to locally reason about how their stylesheets' loads are resolved. If you want to present a fully virtual filesystem, you need to create a full importer yourself.

> BTW, the require statement in the first example at https://sass-lang.com/documentation/js-api/interfaces/FileImporter should be changed to pathToFileURL.

Thanks! Can you file a PR against https://github.com/sass/sass to fix it?

**Comment by MBelniak** [comment]
`Thanks! Can you file a PR against https://github.com/sass/sass to fix it?`
I could if I had push access to that repo. Can you grant it to me?

**Comment by Awjin** [comment]
@MBelniak You need to fork `https://github.com/sass/sass`, make the changes in a branch in your fork, then submit a PR.
