### ISSUE TITLE
dart-sass commandline did not import files when they change

### ISSUE THREAD

**Issue by PapaZivi** [sass/dart-sass#702]
I have organized several projects in such a way that I have a own folder per project (`/projekt1/, /projekt2/, ...`).
Things that I need again and again (`bootstrap/fontawesome/...`) did i put in a separate folder (`/_lib/`).
if I now import something in a project folder from an overlying folder (`../_lib/bla.scss`), than it compiles everything as ist should on startup and on every manually call.
but if i start the commanlinetool with `--watch` or `--watch --poll` changes in the overlying folders are not monitored.

i hope this is a bug and not a feature ;)

i used the precompiled version 1.20.2 from github for linux 64bit (`dart-sass-1.20.2-linux-x64.tar.gz`)

testcase:
folders
```
overindex.scss
_lib/
   | –– _fancythings.scss
sub/
   | –– index.scss
```
_fancythings.scss
```scss
$color: #fff;
```

index.scss
```scss
@import "../_lib/fancythings";
a { color: $color; }
```

overindex.scss
```scss
@import "sub/index";
```

commandlines which not work:
```
sass --watch --poll -s compressed --no-source-map sub/index.scss sub/index.css
sass --watch -s compressed --no-source-map sub/index.scss sub/index.css
```
commandlines which work:
```
sass --watch --poll -s compressed --no-source-map overindex.scss sub/index.css
sass --watch -s compressed --no-source-map overindex.scss sub/index.css
```

**Comment by nex3** [comment]
The Sass compiler needs to choose which directories to watch when you invoke it, and in order to avoid taking up too many resources, it only watches directories containing the input files you pass on the command line as well as load paths. Rather than importing `../_lib/fancythings`, I recommend adding `../_lib` to your load path and writing `@import "fancythings"` instead. Then you can run:

```
sass --watch -s compressed --no-source-map -I ../_lib sub/index.scss sub/index.css
```

**Comment by PapaZivi** [comment]
really?
why should it use more ressources importing a **single** file from `../` rather than `./`?
i dont get it, sorry

**Comment by nex3** [comment]
In order to accurately report changes for a single file, we need to watch the entire directory containing that file. Otherwise, we would produce inconsistent results if the import became ambiguous, for example because `_fancythings.scss` and `fancythings.scss` both existed. What's more, some directory-watching APIs *only* support recursively watching directories, which can result in watching many many unrelated files, which is expensive.

It would also add a lot of code complexity. When we base the directories to watch on the entrypoint paths and load paths, we're able to determine them before we start parsing any Sass files, and they're guaranteed never to change. But if they depend on the contents of the Sass files, we'd need to build infrastructure to dynamically start or stop watching new directories when those Sass files change, which is much much more complex.
