### ISSUE TITLE
Support SourceRoot from CLI

### ISSUE THREAD

**Issue by aronduby** [sass/dart-sass#754]
This doesn't appear to support setting the sourceMap's `sourceRoot` property from the CLI. Other implementations allow setting this by passing in a `source-map-root` argument.

**Comment by nex3** [comment]
What's your concrete use-case for the `sourceRoot` property? If we just added the ability to set it without changing anything else about the source maps, it's likely to either break (in `relative` mode where URLs are relative to the source map path) or do nothing at all (in `absolute` mode where URLs are absolute and thus don't need to be resolved at all).

**Comment by aronduby** [comment]
Sass files for individual packages are processed locally and the css and
map files are uploaded to the server. CSS files are bundled dynamically on
the server and the map files for the individual packages are combined
together into a sectioned source map for the whole bundle. Right now I'm
setting the root when they're combined, but would be nice to have that
pre-proccesed

**Comment by nex3** [comment]
So you'd like to be able to set the `sourceRoot` property to the same directory as the source map itself is in, even though that's redundant with the default base URL?

**Comment by aronduby** [comment]
Yes, because it gets copied and no longer lives at that location at run
time.

**Comment by nex3** [comment]
I don't think it makes sense to allow that to be set via the Sass CLI. It's not something Sass has any special information about, since it's totally dependent on how the files are mounted on your server, so all we could do is pass the user's URL through as-is. It would also be easy for a user to shoot themself in the foot with it if they don't understand exactly what it does, since it can make relative URLs invalid; and it'll silently do nothing with `--source-map-urls=absolute` or `--embed-sources`. Plus it's easy to add after-the-fact as you're doing now, or even with a tool like [`jq`](https://stedolan.github.io/jq/).

**Comment by aronduby** [comment]
Sass doesn't need to know any special information to just pass through a string to the output. It appears that's all node-sass does as well. 

> It would also be easy for a user to shoot themself in the foot with it if they don't understand exactly what it does

Isn't this true of everything? Choosing not to have feature parity and support something because someone is bad at their job seems like a bad argument.

**Comment by nex3** [comment]
> Sass doesn't need to know any special information to just pass through a string to the output. It appears that's all node-sass does as well.

Right, but that also means that the user doesn't get any particular benefit from this being built into Sass as opposed to being part of a post-processing step. For example, Sass supports `--embed-sources` because Sass already knows the contents of the source file that corresponds to each source URL, so it can save the user effort by embedding that information itself. `--source-root` would provide no such benefit.

> > It would also be easy for a user to shoot themself in the foot with it if they don't understand exactly what it does
> 
> Isn't this true of everything? Choosing not to have feature parity and support something because someone is bad at their job seems like a bad argument.

UX design isn't just about making it possible to do the right thing; it's also about making it hard to do the wrong thing. Sometimes it's necessary to prioritize the former, but in this case providing this option would make doing the wrong thing much easier and would provide very limited benefit in exchange.

**Comment by pklauzinski** [comment]
Use case: Mapping `sourceRoot` to a local development environment (e.g. `http://localhost:XXXX`) in order to debug a production issue without exposing the source publicly. This is what I use it for, but after switching from `node-sass` I can no longer compile with this option in the CLI. Additionally, I don't want to use the `absolute` option because it will expose my local file system structure to the public.

**Comment by nex3** [comment]
Why not use `jq` to add the property?

**Comment by rgpublic** [comment]
We are compiling on a different server - that's why we need to prefix the source root paths. Yeah, we could use jq to modify the file, but it's really unnecessarily complicated. Many other tools support adding this value via command-line.

**Comment by nex3** [comment]
Can you provide some examples of other tools that support this?

**Comment by rgpublic** [comment]
@nex3 Sure:

UglifyJS
https://github.com/mishoo/UglifyJS
--source-map root

LightningCSS
https://github.com/parcel-bundler/lightningcss/blob/master/node/index.d.ts
projectRoot

TypeScript
https://www.typescriptlang.org/tsconfig/#sourceRoot
sourceRoot

LessCSS
https://lesscss.org/usage/#less-options-rootpath
--source-map-rootpath

etc. I'd say almost every tool on the web that can produce source maps allows use to change this - except dart-sass.
That's why I don't really understand the discussion about "shooting yourself in the foot" tbh. It's another command-line option. You don't have to use it. If you do, you should know what it's good for. But there are numerous other such options where you can cause problems if you use them and don't know what they're used for. None of the other above mentioned tools seems to have a problem with this.

This is a very useful option for everyone who likes to put the final product of their compilation in a different folder. That's why the original sourceRoot option in the map file exists in the first place. It was invented and is usually configurable for exactly this reason.

**Comment by aronduby** [comment]
I'll add that node-sass has supported this as well
