### ISSUE TITLE
Backslash escapes converted to char

### ISSUE THREAD

**Issue by gabrielmaldi** [sass/dart-sass#79]
Source:

```sass
.ic-icon-ic-more-information:before {
    content: "\e906";
}
```

Output (change from node-sass to dart-sass):

<img width="254" alt="screen shot 2016-12-27 at 12 56 07 pm" src="https://cloud.githubusercontent.com/assets/3728897/21503156/ed8cfeb2-cc33-11e6-9b8e-bf5f662d9ed1.png">

**Comment by nex3** [comment]
I'm pretty sure Dart Sass's output is valid here. It's emitting the Unicode character U+E906, which is semantically identical to the escape sequence `\e906`.

**Comment by gabrielmaldi** [comment]
I filed this issue because the behavior differs from that of node-sass. I'd argue that if the source was written with the escape sequence, the output should be consistent and keep it that way (unless `--style compressed` is specified), but I also understand that it's a matter of personal taste; I like to keep the escape sequence in the output as it's readable, and at build time I run a minifier which actually does turn it into the Unicode char.

Thanks for your time.

**Comment by nex3** [comment]
Sass doesn't store the original format of string values; doing so would be pretty expensive. So we have to decide how to emit non-ASCII characters without reference to how they were originally defined. We choose to emit them as inline Unicode values because that's much more readable in the common case of non-English text, and because it's generally a more compact representation.

**Comment by gabrielmaldi** [comment]
Fair enough. Thanks for the insights.
