### ISSUE TITLE
Interpolation error

### ISSUE THREAD

**Issue by yaquawa** [sass/dart-sass#879]
The following code will throw an error with message "Error: Expected expression."

 ```css
body {
  div {
    $width: 100;
    width: #{$width}0%;
  }
}
```

**Comment by nex3** [comment]
This is intentional. Interpolation in SassScript expressions is parsed as an [`InterpolatedIdentifier`](https://github.com/sass/sass/blob/master/spec/syntax.md#interpolatedidentifier), which means it consumes as many [name code points](https://drafts.csswg.org/css-syntax-3/#name-code-point) as it can. In this case, the `InterpolatedIdentifier` covers `#{$width}0`, but not the `%` because that's not a name code point. Since `%` isn't a valid Sass or CSS property value token on its own, parsing fails.

One way to think about this is whether the expression would still be valid syntax if you replaced the interpolation with an alphabetical character. In this case, you'd get `a0%`, which is not valid.

In general, it's not a good idea to use interpolation to manipulate numbers—you should use [unit arithmetic](https://sass-lang.com/documentation/values/numbers#units) instead. If you want to convert a unitless number to a percentage that's 10x larger, just write:

```scss
body {
 div {
   $width: 100;
   width: $width * 10%;
 }
}
