### ISSUE TITLE
Support <general-enclosed> in @supports

### ISSUE THREAD

**Issue by nex3** [sass/dart-sass#894]
See https://github.com/sass/sass/issues/2780

**Comment by hyfyline** [comment]
> Hi! Since it looks like it'll be a while until this is supported, do you have ideas for a workaround in the mean time? Something that would allow me to do something like this:
> 
> ```css-scss
>   @mixin focus-hl {
>     @supports selector(*:focus-visible) { outline: 1px solid red; }
>   }
> 
>   div { @include focus-hl; }
> ```

Depends on the specifics.
e.g. color
```
            background-color:#000
            background-color: rgba(0, 0, 0, 0.6)
```

Most animations will have to be done by JavaScript and detected with. Otherwise use Modernizr and have a different class set upon it. I can't say this will solve most of the problems. It will limit how you can build your site.

Alternatively, build in a Progressive enhancement manner.

**Comment by janwidmer** [comment]
is this supposed to work now?

```
@supports (:focus-visible) {
    &:focus {
      outline: none;
    }
  }
```

I am still getting an error `SassError: Expected identifier`:
![image](https://user-images.githubusercontent.com/3381820/159585836-06446c64-bd4b-4bf0-b764-9e8c13c0bf57.png)
