### ISSUE TITLE
Does not watch files from other folder

### ISSUE THREAD

**Issue by hansmaad** [sass/dart-sass#967]
This is the file I reference in CLI `src/app/index.scss`:
```
@import '../common/common';
@import 'stuff';
```
Changes in `src/app/_stuff.scss` are successfully detected, but changes to `src/common/_common.scss` are ignored. The inital compilation works as expected.

My command line:
```
sass --load-path=node_modules --watch src/app/index.scss:dist/index.css
```

Installed via npm on win10 as local package.
```
$ npx sass --version
1.26.2 compiled with dart2js 2.7.1
```
`--poll` doesn't change anything.
I can workaround with an additional `--load-path=src` and  change to `@import 'common/common';` but this breaks other builds for me...

**Comment by nex3** [comment]
This is expected; the directory watcher only looks at:

* Directories that you pass as-is on the command line.
* The parent directories of filenames you pass on the command line.
* Load paths.

Watching additional directories based on a file's `@import`/`@use`/`@forward` rules gets *very* complicated, because then the set of directories to watch can change over time as file contents change. This added complexity isn't worth the benefit.

You can always use the JS API to set up your own watcher with more particular logic, if you'd like.

**Comment by Awjin** [comment]
Filed https://github.com/sass/sass-site/pull/580 to improve the docs.

**Comment by ryanb** [comment]
Thank you @Awjin!

**Comment by paulmsmith** [comment]
Lost a bit of time to this today. Could possibly be highlighted more in the documentation. Will use a different watch tool as @nex3 suggests.

**Comment by factoidforrest** [comment]
Watch should really crawl the directory tree, its not actually that difficult.  Many, many other tools do this just fine.  At *least* allow a manually specified list of directories to watch.
