### ISSUE TITLE
Styles loaded through `load-css` aren't recognized as dependencies with flag `--watch`

### ISSUE THREAD

**Issue by cpof-tea** [sass/dart-sass#983]
Here's a simple example
```scss
// input/_partial.scss

.entry__partial { ... }
```
```scss
// input/entry.scss

@use 'sass:meta';

.entry { ... }

// Next, I need to load partial styles from a different file
// I can't use @use or @forward,
// because they must be written before any other rules,
// but in my case order is matter. So I used `load-css`

@include meta.load-css('partial');
```
When I run `sass input:output --watch`, and then update `_partial.scss`, it doesn't recompile `entry.scss`. Turns out, styles loaded through `load-css` aren't recognized as dependencies.
Is it a bug or feature?

p.s. `@import` resolves this behavior now, but it will be depreciated in future

_Linux 18.04.4
node 12.16.2
sass 1.26.3 compiled with dart2js 2.7.1_

**Comment by nex3** [comment]
This is expected. One of the downsides of `meta.load-css()`, and one of the reasons we discourage its use in most situations, is that it can't be statically analyzed in general—that is, there's no way to tell just by looking at the Sass file which module `load-css()` is going to load. Its argument could be a variable that's set far off in a different Sass file, and in `--watch` mode it could even change without anything change without anything changing in the file that actually contains the `meta.load-css()` call.

The Sass watcher relies on static analysis to figure out which files depend on which others. So because `meta.load-css()` isn't statically analyzable, it's effectively invisible to that logic.

It looks like you're using `meta.load-css()` to emit styles in a particular order. A better way to do that would be to put all the styles in your partial into a mixin, and then including that mixin where you want them to go. For example:

```scss
// input/_partial.scss

@mixin styles {
  .entry__partial { ... }
}
```
```scss
// input/entry.scss
@use 'partial';

.entry { ... }

@include partial.styles;
```
