### ISSUE TITLE
Do Not Delete Existing Output CSS File if Compiling Fails

### ISSUE THREAD

**Issue by bdkjones** [sass/dart-sass#995]
I'm using the CLI and passing Dart Sass the input and output paths to use. I am also passing `--no-error-css`.

Currently, if compiling fails, Dart Sass deletes any existing file at the output path. This behavior is less than ideal because most folks integrate the Sass compiler into a larger build chain that does things like auto-refresh a browser preview of their site when files on disk change. Dart Sass's current behavior results in that preview warping to a completely un-styled version of the page because the CSS file has been completely deleted and therefore 404s.

A better alternative would be to leave any *existing* file at the output path in place until compiling has completed successfully and there is new output to write to that location. (Unless the `--no-error-css` option is omitted, in which case the output location gets overwritten with an error stylesheet.)

This would prevent breaking the whole preview and subsequent parts of build chains. And since most compiling errors are simple "oh, duh" moments that take one or two keystrokes to fix, that's much more convenient for the end user.

Reference: https://github.com/bdkjones/CodeKit/issues/610

**Comment by Awjin** [comment]
I'm not sure that this proposed behavior is better for the user.

Say that the user makes an error in their Sass file, but the outputted style and preview of their site stays unchanged. It would be hard to debug whether the Sass code is invalid, or whether the generated CSS is not behaving correctly.

Further, if the CSS is persisted—
> A better alternative would be to leave any existing file at the output path in place until compiling has completed successfully and there is new output to write to that location.

—and the user makes multiple edits without noticing their Sass is broken, it would be really difficult to backtrack their edits and figure out which one broke the build.

It seems to me that deleting the output when compilation fails is a clear and unambiguous signal.

**Comment by bdkjones** [comment]
Respectfully, I think you should reconsider.

Every build process has a very obvious way to surface errors to the user such that it’s not possible to miss them. Whether that’s Webpack, grunt, gulp, CodeKit, or what-have-you.

Additionally, to my knowledge, Dart Sass is the only compiler that behaves this way. I would know—I implement all of them. Everything from Babel to Rollup to Stylus to Less to npm to Autoprefixer to PostCSS to Xcode building actual applications: nothing randomly deletes output files when an error occurs. That behavior is user-hostile.

I can certainly hack around Dart Sass by copying the existing output file and restoring it if Dart Sass fails, but that introduces extra overhead that makes Dart Sass appear slightly slower. I think it would be better if Dart Sass acted the same way other tools in the ecosystem behave.

It’s also worth pointing out that the user would explicitly have to opt-in to this behavior by disabling the error stylesheet, which is on by default.

**Comment by bdkjones** [comment]
I also don’t understand how the user would “have trouble figuring out which edit broke the build”: the error message literally tells them the exact line and column number.

**Comment by nex3** [comment]
> Every build process has a very obvious way to surface errors to the user such that it’s not possible to miss them. Whether that’s Webpack, grunt, gulp, CodeKit, or what-have-you.

All of these builders have their own Sass plugins that can control exactly what happens when they encounter a Sass error. The Sass CLI (particularly `sass --watch`) is specifically designed for running *without* another build system involved, and its UX needs to optimize for that use-case.

I agree with Awjin that silently changing nothing is a bad user experience. CSS has a lot of ways for various inputs to silently do nothing, whether it's because a selector was typo'd and ignored by the browser or because your `height` property conflicts with a `min-height` somewhere totally different. A user who accidentally writes invalid Sass code may assume their error was one of these and spend a lot of time and frustration in the dev console trying to figure out why a new property they added isn't showing up on their page before they even think to check their terminal to see the error message.

"Other tools do it differently" is a meaningful data point but it doesn't outweigh the concrete scenarios of user frustration that Awjin and I have described. A more compelling argument would be a use-case where the current behavior actually hurts users. You've said it's "user-hostile", but you haven't explained why.

**Comment by bdkjones** [comment]
Fair points. And I think the CLI’s current default (printing an error stylesheet when something goes wrong) alleviates all of the concerns you’ve described.

But when a user explicitly passes the flag to disable that error stylesheet, what they mean is: “Don’t modify my existing compiled-CSS; I already have a good way to receive errors.”

As for actively harming users: the original harm that sparked my request is described in the linked issue on the CodeKit repo (above). One of my users has a complex site that breaks when it is auto-refreshed after Dart Sass deletes the CSS output file and, to restore the site to a working state, the user must manually reload the page in the browser after fixing the Sass error. He cannot rely on CodeKit’s automatic injection reload process, which reloads just the page’s stylesheets.

**Comment by Ariane-B** [comment]
I fully agree with @bdkjones. I do not want my errors to be huge and enormously visible in my browser window. I use the console output for that. *If* I want extremely aggressive error reporting such that any error to destroy everything, I will tell Sass.

Making this the default is debatable, and I understand why you disagree about our opinion about the UX. But it *must* be optional. Completely deleting something that used to work because I made a typo is not acceptable behaviour to me at all, and I should be able to decide whether I want that, the same way I'm able to decide whether, say, CodeKit throws a notification when there's an error.

Another point to add: the browser's behaviour when it encounters a 404 on a stylesheet file is erratic. Actually, I'm not even sure it's the browser. It could also be PHP's hard-to-disable built-in cache, or Nginx. I may never know, because really, the server side of things is not my cup of tea. The point is, it appears that something in my work stack, be it the browser or VVV (a distributed development machine -- hardly highly custom material) does not handle temporarily 404-ed stylesheets well.

I've tried it in both Chrome and Firefox, and when there's an error and the CSS disappears then comes back, *no* amount of hard-refreshing `Cmd-Shift-R`-ing will make it load my stylesheet properly.

I "just" need to wait several seconds (up to 30) until it realizes the stylesheet exists, and then I can finally see my website again. That happens *every* time I make a typo in my Sass. For a sort of error reporting I don't need in the slightest, since CodeKit went "dong" the second Dart had an error anyway. I probably didn't even need to look at the error message. 90% of the time, I hear "dong", I take a second look at my code and I see instantly what I did wrong.

Anyway, in that light, it might be good to reconsider the whole "deleting the file" thing. A very similar behaviour could be achieved by leaving it in place but emptying it (or potentially just putting a comment with the Sass error details into it). That would achieve your goal of completely destroying the style whenever there's an error, but wouldn't cause weird bugs because of the file being missing.

**Comment by nex3** [comment]
You two are claiming that the `--no-error-css` flag *means* "don't do anything error-related with the output stylesheet", but that's not accurate. I believe there are plenty of users out there who want the current behavior for the reasons I described above.

The use-cases you're describing are all full of layers of complex post-processing. I'll reiterate that the Dart Sass command-line executable is designed first and foremost as a user interface for direct interaction; if you're trying to do particularly complex integrations, you'd be better off using one of the several programmatic interfaces we provide, which are much more customizable.

**Comment by bdkjones** [comment]
Well, it’s easy enough to work around the behavior. But I do think this decision should be revisited. For example, perhaps you should only delete the output file if the CLI is running —watch, which would imply it’s in the background somewhere and the user isn’t directly interacting with it.

If the user IS directly running the command, showing the error in the Terminal is sufficient.

I mean, can you imagine if you made a typo in your package.json file and npm just nuked all 843 packages in your node_modules folder when you ran “update” to make it more clear that you screwed up?

**Comment by Ariane-B** [comment]
That's not what the option means. All right, we misunderstood its purpose. But you are sidestepping the heart of my argument.

My primary point is that it is absolutely not reasonable for there to be no way at all to ask Sass not to destroy everything as soon as it stubs its toe. That there are plenty of users out there that want absolute destruction... honestly, I don't understand them, but that's not important. They have different expectations than mine, and that's fine.

What is not fine is that it's the only option. I ultimately don't really care what the way to change it is. It could be an additional option named `--dont-delete-on-error`. It could be literally anything. I just find it utterly unacceptable that there wouldn't be a way to tell Sass not to knock everything down as soon as it stubs its toe. Because the 404 issue is real, and major.

**Comment by bdkjones** [comment]
@Ariane-B Gotta be careful about unilaterally declaring things to be unacceptable. There’s a difference of opinion on how this detail should work, certainly, but we may not have the full picture. It’s always best to assume the developer of a given project has some expertise or experience we, as users, may lack. And it doesn’t really matter because CodeKit will work around this behavior with the next update.

@nex3 The reason I use the CLI interface is that the only other pre-built API interface is the JavaScript one, which is slower than using the Dart VM. (I guess that interface is what node-sass uses when it compiles with Dart Sass?) A great many apps, including Xcode itself, work like this—they set up a call to a CLI and execute it.

I *could* write my own Dart interface by forking the existing CLI and modifying it, but that obviously entails a lot of checking to make sure my fork stays up to date, nothing breaks, and new features get added. For that reason, I greatly prefer relying on the official implementations.

**Comment by bdkjones** [comment]
Additionally: while testing to implement the workaround discussed above, I discovered that Dart Sass is not consistent. It deletes the original CSS output file, but leaves the original source map file in place. If that behavior is intentional and will remain, that's one fewer thing I need to copy and store before attempting to compile with Dart Sass, so I'm not opposed.

**Comment by Ariane-B** [comment]
I'm sorry. I should definitely not have been so intense in my arguing. I may be a bit too emotional for this, so I should retire from this thread. I hope I didn't spook everyone too much. Have a nice day!

**Comment by quasipickle** [comment]
Even if there are other build tools one could use, and the use cases are fairly narrow, I see no practical or technical reason why this behaviour can't be modified with a flag.  Not creating error CSS is an opt-in behaviour, so not nuking from orbit can also be an opt-in behaviour.  It will change literally nothing unless the user specifically requests it.
